window.NLDG_ARTICLES=[
{id:'grace-accountability',slug:'grace-accountability',title:'Grace Does Not Erase Accountability',excerpt:'Biblical grace tells the truth about sin while protecting the dignity of the person who needs restoration.',category:'Christian Living',series:'Everyday Discipleship',author:'Dexter Graham',publishedAt:'2026-07-26',readingTime:6,featured:true,scripture:['John 1:14','Galatians 6:1-2'],topics:['grace','accountability','restoration','truth'],content:[
{heading:'Grace and truth belong together',paragraphs:['Jesus did not choose between grace and truth. John describes Him as full of both. Grace without truth can become permission, while truth without grace can become condemnation. The way of Jesus confronts what is wrong while still seeing a person made in the image of God.']},
{heading:'Accountability is meant to restore',paragraphs:['Biblical accountability is not public humiliation or a desire to make someone suffer. It is the loving work of helping one another return to faithfulness. Galatians 6 tells spiritual believers to restore gently and to watch their own hearts while doing it.']},
{heading:'Dignity remains',paragraphs:['A person may need correction, boundaries, consequences, or time to rebuild trust. None of those things remove their God-given worth. Christians should be able to insist on responsibility without cruelty and offer mercy without pretending that harm did not occur.']}
],questions:['Do you tend to emphasize grace or accountability more strongly?','How can correction become restorative rather than humiliating?','Where might God be calling you to combine truth with gentleness?'],prayer:'Lord, teach me to speak truth without pride and extend grace without compromise. Help me seek restoration, protect dignity, and reflect the heart of Jesus.'},
{id:'faith-hard-seasons',slug:'faith-hard-seasons',title:'Faith in Hard Seasons',excerpt:'Hard seasons can change our routines, our confidence, and our plans, but they cannot remove the presence of God.',category:'Testimonies & Reflections',series:'Faith in Real Life',author:'Dexter Graham',publishedAt:'2026-07-25',readingTime:5,featured:true,scripture:['Psalm 46:1','Isaiah 41:10'],topics:['hope','suffering','endurance','presence of God'],content:[
{heading:'Faith does not deny difficulty',paragraphs:['Trusting God does not require us to pretend that pain is easy. Scripture gives us permission to lament, ask questions, and acknowledge weakness. Faith begins by bringing the truth of our experience into the presence of God.']},
{heading:'God often works through people',paragraphs:['During difficult seasons, God frequently makes His care visible through family, church members, nurses, friends, and even strangers. Receiving help is not a failure of faith. It can be one of the ways we experience the body of Christ.']},
{heading:'Strength comes one day at a time',paragraphs:['We often want the full plan, but God commonly gives enough grace for the present day. Endurance grows through small acts of trust: praying again, showing up again, accepting help, and believing that God is still present.']}
],questions:['What has a hard season revealed about your faith?','Who has God used to support you?','What does faithfulness look like for you today?'],prayer:'God, be my refuge and strength. Help me trust You one day at a time and recognize Your presence in the people and grace You provide.'},
{id:'truth-online',slug:'truth-online',title:'Before You Share: Truth, Discernment, and Social Media',excerpt:'Christian witness includes what we post, repeat, and endorse online.',category:'Faith & Today’s World',series:'Following Jesus Online',author:'Dexter Graham',publishedAt:'2026-07-24',readingTime:7,featured:false,scripture:['Proverbs 14:15','James 3:5-10'],topics:['discernment','social media','misinformation','witness'],content:[
{heading:'Speed works against wisdom',paragraphs:['Social media rewards immediate reactions. Biblical wisdom asks us to slow down, examine a claim, and consider the effect of our words before sharing them. Being first is not more important than being truthful.']},
{heading:'Our witness travels with our words',paragraphs:['A post may feel temporary, but it can influence how others see our character and our faith. Christians should care not only whether a message supports their position, but whether it is accurate, necessary, and expressed in a Christlike way.']},
{heading:'Practice a holy pause',paragraphs:['Before posting, check the source, look for reliable confirmation, read beyond the headline, and pray. Sometimes the most faithful response is correction. Sometimes it is silence.']}
],questions:['What makes you most likely to share something quickly?','How can misinformation damage Christian witness?','What practice could help you pause before posting?'],prayer:'Lord, give me wisdom before I speak or share. Let my words be truthful, helpful, and shaped by the character of Christ.'},
{id:'church-shows-up',slug:'church-shows-up',title:'When the Church Shows Up',excerpt:'The church becomes visible when ordinary believers carry burdens, meet needs, and stay present.',category:'Church & Ministry',series:'The Church in Action',author:'Dexter Graham',publishedAt:'2026-07-23',readingTime:6,featured:false,scripture:['Galatians 6:2','Acts 2:42-47'],topics:['church','community','service','compassion'],content:[
{heading:'More than a weekly gathering',paragraphs:['The church gathers for worship and teaching, but its life cannot end when the service closes. Acts 2 describes believers sharing meals, prayers, resources, and daily life. Their fellowship became a visible testimony.']},
{heading:'Presence is ministry',paragraphs:['Not every need can be fixed. Sometimes ministry means listening, sitting with someone, making a call, providing a ride, preparing a meal, or remembering to check again tomorrow. Presence communicates that people are not forgotten.']},
{heading:'Everyone has something to carry',paragraphs:['The ministry of the church is not limited to pastors. Every believer can encourage, serve, pray, give, teach, visit, or help. When everyone carries part of the burden, the love of Christ becomes tangible.']}
],questions:['When has someone from the church shown up for you?','What practical need can you help carry this week?','How can your congregation become more present in the community?'],prayer:'Jesus, make Your church a living expression of Your compassion. Show me whose burden I can help carry and give me the willingness to be present.'}
];
window.NLDG_ARTICLE_API={all:()=>[...window.NLDG_ARTICLES],bySlug:slug=>window.NLDG_ARTICLES.find(item=>item.slug===slug),featured:()=>window.NLDG_ARTICLES.filter(item=>item.featured),categories:()=>[...new Set(window.NLDG_ARTICLES.map(item=>item.category))],related:(article,limit=3)=>window.NLDG_ARTICLES.filter(item=>item.id!==article.id).map(item=>({item,score:item.category===article.category?3:(item.topics||[]).filter(topic=>(article.topics||[]).includes(topic)).length})).sort((a,b)=>b.score-a.score).slice(0,limit).map(result=>result.item)};