(()=>{
if(window.NLDG_ARTICLE_LIBRARY_LOADED||!window.NLDG_LIBRARY)return;
const items=[
 {id:'article-family-nobody-talks-about',type:'Article',title:'The Family Nobody Talks About',description:'Three mornings a week, a room full of strangers becomes something more through shared burdens, quiet prayers, and the simple act of showing up.',url:'articles/family-nobody-talks-about.html',category:'Testimonies & Reflections',series:'Faith in Real Life',scripture:[],book:'',topics:['dialysis','community','prayer','shared burdens','hope'],audience:['Individuals','Families','Churches'],difficulty:'All Levels',duration:4,featured:true,status:'published',publishedAt:'2026-07-16',updatedAt:'2026-07-30'},
 {id:'article-grace-accountability',type:'Article',title:'Grace Does Not Erase Accountability',description:'Biblical grace tells the truth about sin while protecting the dignity of the person who needs restoration.',url:'articles/grace-accountability.html',category:'Christian Living',series:'Everyday Discipleship',scripture:['John 1:14','Galatians 6:1-2'],book:'Various',topics:['grace','accountability','restoration','truth','dignity'],audience:['Individuals','Small Groups','Churches'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-26',updatedAt:'2026-07-30'},
 {id:'article-faith-hard-seasons',type:'Article',title:'Faith in Hard Seasons',description:'Hard seasons can change our routines, our confidence, and our plans, but they cannot remove the presence of God.',url:'articles/faith-hard-seasons.html',category:'Testimonies & Reflections',series:'Faith in Real Life',scripture:['Psalm 46:1','Isaiah 41:10'],book:'Various',topics:['hope','suffering','endurance','presence of God'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-25',updatedAt:'2026-07-30'},
 {id:'article-truth-online',type:'Article',title:'Before You Share: Truth, Discernment, and Social Media',description:'Christian witness includes what we post, repeat, and endorse online.',url:'articles/truth-online.html',category:'Faith & Today’s World',series:'Following Jesus Online',scripture:['Proverbs 14:15','James 3:5-10'],book:'Various',topics:['discernment','social media','misinformation','witness'],audience:['Individuals','Families','Small Groups','Churches'],difficulty:'All Levels',duration:7,featured:false,status:'published',publishedAt:'2026-07-24',updatedAt:'2026-07-30'},
 {id:'article-church-shows-up',type:'Article',title:'When the Church Shows Up',description:'The church becomes visible when ordinary believers carry burdens, meet needs, and stay present.',url:'articles/church-shows-up.html',category:'Church & Ministry',series:'The Church in Action',scripture:['Galatians 6:2','Acts 2:42-47'],book:'Various',topics:['church','community','service','compassion','presence'],audience:['Individuals','Small Groups','Churches','Leaders'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-23',updatedAt:'2026-07-30'},
 {id:'article-jesus-loves-you',type:'Article',title:'Jesus Loves You',description:'A sign declaring “Jesus Loves You” carries a powerful message. Christians are called to make those words visible through compassion, kindness, and action.',url:'articles/jesus-loves-you.html',category:'Christian Living',series:'Everyday Discipleship',scripture:['John 13:34-35','1 John 3:18'],book:'John',topics:['Jesus’ love','Christian witness','compassion','service','kindness','discipleship','church'],audience:['Individuals','Families','Small Groups','Churches'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'}
];
const existing=new Set(window.NLDG_LIBRARY.map(item=>item.id));
window.NLDG_LIBRARY.push(...items.filter(item=>!existing.has(item.id)));
window.NLDG_STUDIES=window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT=window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_ARTICLE_LIBRARY_LOADED=true;
})();
