window.NLDG_LIBRARY = [
  {id:'identity',type:'Study',title:'Learning to See Yourself Through God’s Eyes',description:'Discover how grace, purpose, and identity come together in Christ.',url:'study-identity.html',category:'Identity in Christ',series:'Foundations of Faith',scripture:['Ephesians 2:1-10'],book:'Ephesians',topics:['identity','grace','purpose'],audience:['New Believers','Small Groups'],difficulty:'Beginner',duration:45,featured:true,status:'published',publishedAt:'2026-07-01',updatedAt:'2026-07-21'},
  {id:'escapism',type:'Study',title:'Escapism vs. Eternal Hope',description:'Learn the difference between avoiding responsibility and living with eternal perspective.',url:'study-escapism.html',category:'Faith & Today’s World',series:'Faith & Truth in Today’s World',scripture:['Colossians 3:1-4'],book:'Colossians',topics:['hope','culture','discipleship'],audience:['Adults','Small Groups'],difficulty:'Intermediate',duration:50,featured:false,status:'published',publishedAt:'2026-07-02',updatedAt:'2026-07-21'},
  {id:'free-indeed',type:'Study',title:'Free Indeed',description:'Explore the freedom Christ gives and the habits that help us walk in it.',url:'study-free-indeed.html',category:'Brotherhood',series:'Brotherhood Bible Studies',scripture:['John 8:31-36'],book:'John',topics:['freedom','discipleship','spiritual growth'],audience:['Men’s Ministry','Small Groups'],difficulty:'All Levels',duration:40,featured:false,status:'published',publishedAt:'2026-07-03',updatedAt:'2026-07-21'},
  {id:'storm',type:'Study',title:'Faith in the Storm',description:'A study for hard seasons when fear is loud and Jesus seems quiet.',url:'study-storm.html',category:'Hope & Endurance',series:'Following Jesus',scripture:['Mark 4:35-41'],book:'Mark',topics:['hope','fear','trust','grief','hard seasons'],audience:['New Believers','Adults'],difficulty:'Beginner',duration:35,featured:false,status:'published',publishedAt:'2026-07-04',updatedAt:'2026-07-21'},
  {id:'peacemakers',type:'Study',title:'Peacemakers in a Divided World',description:'Practice biblical peacemaking without surrendering truth or dignity.',url:'study-peacemakers.html',category:'Faith & Today’s World',series:'Faith & Truth in Today’s World',scripture:['Matthew 5:9'],book:'Matthew',topics:['peace','culture','community'],audience:['Adults','Church Leadership'],difficulty:'Intermediate',duration:55,featured:false,status:'published',publishedAt:'2026-07-05',updatedAt:'2026-07-21'},
  {id:'grace-accountability',type:'Study',title:'Grace and Accountability',description:'Grace does not erase accountability, and accountability does not erase dignity.',url:'study-grace-accountability.html',category:'Christian Living',series:'Following Jesus',scripture:['John 1:14'],book:'John',topics:['grace','truth','dignity'],audience:['Adults','Small Groups'],difficulty:'All Levels',duration:45,featured:false,status:'published',publishedAt:'2026-07-06',updatedAt:'2026-07-21'},
  {id:'daily-devotionals',type:'Devotional',title:'Daily Devotionals',description:'Short biblical encouragement for identity, faith, peace, and discipleship.',url:'devotionals.html',topics:['daily','devotional','encouragement'],audience:['Individuals','Families'],status:'published'},
  {id:'faith-articles',type:'Article',title:'Articles on Faith and Today’s World',description:'Biblical reflection on identity, discipleship, culture, and everyday life.',url:'articles.html',topics:['articles','culture','faith','identity'],audience:['Adults'],status:'published'},
  {id:'ministry-resources',type:'Resource',title:'Ministry Resources',description:'Practical tools for families, small groups, teachers, and church leaders.',url:'resources.html',topics:['leader guide','family','small group','church'],audience:['Leaders','Families'],status:'published'},
  {id:'no-labels-podcast',type:'Podcast',title:'The No Labels Podcast',description:'Biblical conversations about identity, family, discipleship, culture, and following Jesus.',url:'podcast.html',topics:['listen','audio','family','identity','conversation'],status:'published'},
  {id:'ministry-updates',type:'News',title:'Ministry Platform Updates',description:'News and updates from No Labels, Designed by God.',url:'news.html',topics:['update','ministry','platform'],status:'published'}
];
window.NLDG_STUDIES = window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT = window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_LIBRARY_API = {
  all:()=>[...window.NLDG_LIBRARY],
  published:()=>window.NLDG_LIBRARY.filter(item=>item.status==='published'),
  byType:type=>window.NLDG_LIBRARY.filter(item=>item.type===type&&item.status==='published'),
  byId:id=>window.NLDG_LIBRARY.find(item=>item.id===id),
  newest:(limit=6)=>window.NLDG_LIBRARY.filter(item=>item.status==='published').sort((a,b)=>String(b.publishedAt||b.updatedAt||'').localeCompare(String(a.publishedAt||a.updatedAt||''))).slice(0,limit)
};
