(()=>{
if(window.NLDG_CONTACT_LIBRARY_LOADED||!window.NLDG_LIBRARY)return;
const items=[
 {id:'contact-feedback',type:'Ministry Page',title:'Contact & Feedback',description:'Contact the No Labels, Designed by God team with questions, prayer requests, website feedback, resource suggestions, or collaboration inquiries.',url:'contact.html#contact',category:'Ministry Information',series:'No Labels, Designed by God',scripture:[],book:'',topics:['contact','email','prayer request','feedback','resource suggestion','collaboration','ministry inquiry'],audience:['Individuals','Families','Small Groups','Churches','Leaders'],difficulty:'All Levels',duration:2,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-08-20'},
 {id:'prayer-center',type:'Prayer Resource',title:'Prayer Center',description:'Submit a private prayer request, request public sharing after review, pray for approved requests, and share answered-prayer updates with privacy and safety safeguards.',url:'prayer.html',category:'Prayer',series:'No Labels, Designed by God',scripture:[],book:'',topics:['prayer','prayer request','prayer wall','private prayer','public prayer','answered prayer','prayer care','intercession'],audience:['Individuals','Families','Small Groups','Churches','Leaders'],difficulty:'All Levels',duration:3,featured:false,status:'published',publishedAt:'2026-08-20',updatedAt:'2026-08-20'},
 {id:'biblical-maps',type:'Reference Resource',title:'Biblical Maps & Geography',description:'Explore an accuracy-conscious biblical geography library covering the world of the Bible, Abraham, the Exodus, Israel’s kingdoms, exile, Jesus, Jerusalem, and Paul.',url:'biblical-maps.html',category:'Biblical Reference',series:'Biblical Maps Reference Atlas',scripture:['Genesis 11–22','Exodus–Deuteronomy','Matthew–John','Acts 13–28'],book:'Various',topics:['biblical maps','geography','Bible lands','Abraham','Exodus','Israel','Jesus','Jerusalem','Paul'],audience:['Individuals','Small Groups','Churches','Teachers','Leaders'],difficulty:'All Levels',duration:5,featured:true,status:'published',publishedAt:'2026-08-29',updatedAt:'2026-08-29'},
 {id:'biblical-people-genealogy',type:'Reference Resource',title:'Complete Biblical People & Genealogy Reference',description:'Search named biblical people, stated family connections, clans, nations, roles, alternate names, and Scripture references across all 66 books while keeping uncertainty visible.',url:'biblical-people-genealogy.html',category:'Biblical Reference',series:'Biblical People & Genealogy',scripture:['Genesis–Revelation'],book:'Various',topics:['biblical people','genealogy','family lines','Bible reference','clans','tribes'],audience:['Individuals','Small Groups','Churches','Teachers','Leaders'],difficulty:'All Levels',duration:5,featured:true,status:'published',publishedAt:'2026-08-29',updatedAt:'2026-08-29'},
 {id:'genealogy-of-jesus',type:'Reference Resource',title:'Genealogy of Jesus Reference',description:'Compare Matthew 1 and Luke 3, trace the major family-line anchors, and see where the Gospel genealogies agree, differ, and require interpretive care.',url:'genealogy-of-jesus.html',category:'Biblical Reference',series:'Biblical People & Genealogy',scripture:['Matthew 1:1–17','Luke 3:23–38'],book:'Gospels',topics:['Jesus','genealogy','Matthew','Luke','David','Abraham'],audience:['Individuals','Small Groups','Churches','Teachers','Leaders'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-08-29',updatedAt:'2026-08-29'}
];
const existing=new Set(window.NLDG_LIBRARY.map(entry=>entry.id));
window.NLDG_LIBRARY.push(...items.filter(item=>!existing.has(item.id)));
window.NLDG_STUDIES=window.NLDG_LIBRARY.filter(entry=>entry.type==='Study'&&entry.status==='published');
window.NLDG_CONTENT=window.NLDG_LIBRARY.filter(entry=>entry.status==='published');
window.NLDG_CONTACT_LIBRARY_LOADED=true;
})();