window.NLDG_LIBRARY = [
  {id:'identity',type:'Study',title:'Learning to See Yourself Through God’s Eyes',description:'Discover how grace, purpose, and identity come together in Christ.',url:'study-identity.html',category:'Identity in Christ',series:'Foundations of Faith',scripture:['Ephesians 2:1-10'],book:'Ephesians',topics:['identity','grace','purpose'],audience:['New Believers','Small Groups'],difficulty:'Beginner',duration:45,featured:true,status:'published',publishedAt:'2026-07-01',updatedAt:'2026-07-21'},
  {id:'42-week-current-events',type:'Study',title:'42 Week Current Events',description:'Faith and truth for today’s world through independent weekly lessons, Scripture, discussion, prayer, and application.',url:'current-events-series.html',category:'Faith & Today’s World',series:'Faith & Truth in Today’s World',scripture:['John 14:6','2 Timothy 3:16-17','Galatians 2:20'],book:'Various',topics:['current events','truth','discernment','culture','faith'],audience:['Adults','Sunday School','Small Groups'],difficulty:'All Levels',duration:50,featured:true,status:'published',publishedAt:'2026-07-24',updatedAt:'2026-07-26'},
  {id:'escapism',type:'Study',title:'Escapism vs. Eternal Hope',description:'Learn the difference between avoiding responsibility and living with eternal perspective.',url:'study-escapism.html',category:'Faith & Today’s World',series:'Faith & Truth in Today’s World',scripture:['Colossians 3:1-4'],book:'Colossians',topics:['hope','culture','discipleship'],audience:['Adults','Small Groups'],difficulty:'Intermediate',duration:50,featured:false,status:'published',publishedAt:'2026-07-02',updatedAt:'2026-07-21'},
  {id:'free-indeed',type:'Study',title:'Free Indeed',description:'Explore the freedom Christ gives and the habits that help us walk in it.',url:'study-free-indeed.html',category:'Brotherhood',series:'Brotherhood Bible Studies',scripture:['John 8:31-36'],book:'John',topics:['freedom','discipleship','spiritual growth'],audience:['Men’s Ministry','Small Groups'],difficulty:'All Levels',duration:40,featured:false,status:'published',publishedAt:'2026-07-03',updatedAt:'2026-07-21'},
  {id:'storm',type:'Study',title:'Faith in the Storm',description:'A study for hard seasons when fear is loud and Jesus seems quiet.',url:'study-storm.html',category:'Hope & Endurance',series:'Following Jesus',scripture:['Mark 4:35-41'],book:'Mark',topics:['hope','fear','trust','grief','hard seasons'],audience:['New Believers','Adults'],difficulty:'Beginner',duration:35,featured:false,status:'published',publishedAt:'2026-07-04',updatedAt:'2026-07-21'},
  {id:'peacemakers',type:'Study',title:'Peacemakers in a Divided World',description:'Practice biblical peacemaking without surrendering truth or dignity.',url:'study-peacemakers.html',category:'Faith & Today’s World',series:'Faith & Truth in Today’s World',scripture:['Matthew 5:9'],book:'Matthew',topics:['peace','culture','community'],audience:['Adults','Church Leadership'],difficulty:'Intermediate',duration:55,featured:false,status:'published',publishedAt:'2026-07-05',updatedAt:'2026-07-21'},
  {id:'grace-accountability',type:'Study',title:'Grace and Accountability',description:'Grace does not erase accountability, and accountability does not erase dignity.',url:'study-grace-accountability.html',category:'Christian Living',series:'Following Jesus',scripture:['John 1:14'],book:'John',topics:['grace','truth','dignity'],audience:['Adults','Small Groups'],difficulty:'All Levels',duration:45,featured:false,status:'published',publishedAt:'2026-07-06',updatedAt:'2026-07-21'},
  {id:'sunday-school-library',type:'Lesson Library',title:'Sunday School Lessons',description:'A reusable archive for Scripture-centered Sunday school lessons, discussion questions, application, and prayer.',url:'sunday-school.html',topics:['Sunday school','teaching','lesson plans','Bible study'],audience:['Teachers','Adults','Small Groups'],featured:true,status:'published',publishedAt:'2026-07-24'},
  {id:'daily-devotionals',type:'Devotional',title:'Daily Devotionals',description:'Short biblical encouragement for identity, faith, peace, and discipleship.',url:'devotionals.html',topics:['daily','devotional','encouragement'],audience:['Individuals','Families'],featured:true,status:'published',publishedAt:'2026-07-07'},
  {id:'faith-articles',type:'Article Library',title:'Article & Writing Center',description:'Biblical truth, practical faith, and thoughtful reflections on following Jesus, culture, ministry, and everyday life.',url:'articles.html',category:'Articles & Writing',series:'No Labels Writing Center',scripture:['John 1:14','Psalm 46:1','Proverbs 14:15','Galatians 6:2'],topics:['articles','writing','culture','faith','Christian living','testimony','ministry'],audience:['Adults','Leaders','Individuals'],featured:true,status:'published',publishedAt:'2026-07-26',updatedAt:'2026-07-26'},
  {id:'article-grace-accountability',type:'Article',title:'Grace Does Not Erase Accountability',description:'Biblical grace tells the truth about sin while protecting the dignity of the person who needs restoration.',url:'article.html?slug=grace-accountability',category:'Christian Living',series:'Everyday Discipleship',scripture:['John 1:14','Galatians 6:1-2'],book:'John',topics:['grace','accountability','restoration','truth'],audience:['Adults','Small Groups'],status:'published',publishedAt:'2026-07-26'},
  {id:'article-faith-hard-seasons',type:'Article',title:'Faith in Hard Seasons',description:'Hard seasons can change our routines, our confidence, and our plans, but they cannot remove the presence of God.',url:'article.html?slug=faith-hard-seasons',category:'Testimonies & Reflections',series:'Faith in Real Life',scripture:['Psalm 46:1','Isaiah 41:10'],book:'Psalms',topics:['hope','suffering','endurance'],audience:['Adults','Individuals'],status:'published',publishedAt:'2026-07-25'},
  {id:'article-truth-online',type:'Article',title:'Before You Share: Truth, Discernment, and Social Media',description:'Christian witness includes what we post, repeat, and endorse online.',url:'article.html?slug=truth-online',category:'Faith & Today’s World',series:'Following Jesus Online',scripture:['Proverbs 14:15','James 3:5-10'],book:'Proverbs',topics:['discernment','social media','misinformation'],audience:['Adults','Students'],status:'published',publishedAt:'2026-07-24'},
  {id:'article-church-shows-up',type:'Article',title:'When the Church Shows Up',description:'The church becomes visible when ordinary believers carry burdens, meet needs, and stay present.',url:'article.html?slug=church-shows-up',category:'Church & Ministry',series:'The Church in Action',scripture:['Galatians 6:2','Acts 2:42-47'],book:'Acts',topics:['church','community','service','compassion'],audience:['Adults','Leaders'],status:'published',publishedAt:'2026-07-23'},
  {id:'no-labels-games',type:'Game',title:'No Labels Games',description:'Interactive Bible learning for families, small groups, and church gatherings.',url:'play.html',topics:['games','Bible','family','small group','interactive'],audience:['Families','Small Groups','Churches'],featured:true,status:'published',publishedAt:'2026-07-09'},
  {id:'leader-guides',type:'Leader Guide',title:'Leader Guides',description:'Preparation notes, discussion helps, timing suggestions, and follow-up tools for ministry leaders.',url:'resources.html',topics:['leader','teaching','facilitation'],audience:['Leaders','Church Leadership'],status:'published'},
  {id:'printable-studies',type:'Printable Study',title:'Printable Studies',description:'Printer-friendly Bible studies for personal use, classes, and small groups.',url:'studies.html',topics:['printable','study','handout'],audience:['Individuals','Small Groups'],status:'published'},
  {id:'family-devotions',type:'Family Devotion',title:'Family Devotions',description:'Faith-building conversations and Scripture activities designed for the home.',url:'devotionals.html',topics:['family','devotion','children','home'],audience:['Families'],status:'published'},
  {id:'teaching-slides',type:'Teaching Slides',title:'Teaching Slides',description:'Presentation-ready visual support for Bible lessons and ministry gatherings.',url:'resources.html',topics:['slides','presentation','teaching'],audience:['Teachers','Leaders'],status:'published'},
  {id:'prayer-resources',type:'Prayer Resource',title:'Prayer Resources',description:'Guides and prompts for personal prayer, families, and ministry groups.',url:'resources.html',topics:['prayer','guide','spiritual growth'],audience:['Individuals','Families','Small Groups'],status:'published'},
  {id:'small-group-resources',type:'Small Group Resource',title:'Small Group Resources',description:'Discussion tools and practical materials that help groups grow together.',url:'resources.html',topics:['small group','discussion','community'],audience:['Small Groups','Leaders'],status:'published'},
  {id:'no-labels-podcast',type:'Podcast',title:'The No Labels Podcast',description:'Biblical conversations about identity, family, discipleship, culture, and following Jesus.',url:'podcast.html',topics:['listen','audio','family','identity','conversation'],featured:true,status:'published',publishedAt:'2026-07-10'},
  {id:'ministry-updates',type:'News',title:'Ministry Platform Updates',description:'News and updates from No Labels, Designed by God.',url:'news.html',topics:['update','ministry','platform'],status:'published'}
];
window.NLDG_STUDIES = window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT = window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_LIBRARY_API = {
  all:()=>[...window.NLDG_LIBRARY],
  published:()=>window.NLDG_LIBRARY.filter(item=>item.status==='published'),
  byType:type=>window.NLDG_LIBRARY.filter(item=>item.type===type&&item.status==='published'),
  byId:id=>window.NLDG_LIBRARY.find(item=>item.id===id),
  newest:(limit=6)=>window.NLDG_LIBRARY.filter(item=>item.status==='published').sort((a,b)=>String(b.publishedAt||b.updatedAt||'').localeCompare(String(a.publishedAt||a.updatedAt||''))).slice(0,limit),
  related:(itemOrId,limit=3)=>{const item=typeof itemOrId==='string'?window.NLDG_LIBRARY.find(entry=>entry.id===itemOrId):itemOrId;if(!item)return[];const terms=new Set([item.type,item.category,item.series,item.book,...(item.topics||[]),...(item.audience||[])].filter(Boolean).map(value=>String(value).toLowerCase()));return window.NLDG_LIBRARY.filter(entry=>entry.status==='published'&&entry.id!==item.id).map(entry=>({entry,score:[entry.type,entry.category,entry.series,entry.book,...(entry.topics||[]),...(entry.audience||[])].filter(Boolean).reduce((total,value)=>total+(terms.has(String(value).toLowerCase())?1:0),0)})).sort((a,b)=>b.score-a.score).slice(0,limit).map(result=>result.entry);}
};