(()=>{
if(window.NLDG_DEVOTIONAL_LIBRARY_LOADED||!window.NLDG_LIBRARY)return;
const items=[
 {id:'devotional-when-god-feels-silent',type:'Devotional',title:'When God Feels Silent',description:'There are seasons when God seems silent, but His silence is never His absence. Learn to trust His faithfulness even when you cannot hear His voice.',url:'devotional.html?id=when-god-feels-silent',category:'Faith',series:'No Labels Devotionals',scripture:['Psalm 13:1-6','Psalm 13:5-6'],book:'Psalms',topics:['faith','waiting','unanswered prayer','God’s presence','trust','lament','unfailing love'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-28'},
 {id:'devotional-the-courage-to-lead',type:'Devotional',title:'The Courage to Lead',description:'Godly leadership does not require us to be fearless. It requires us to trust that God is with us and move forward with courage, integrity, and faith.',url:'devotional.html?id=the-courage-to-lead',category:'Godly Leadership',series:'Brotherhood Devotionals',scripture:['Joshua 1:9'],book:'Joshua',topics:['leadership','courage','faith','integrity','character','service','fear'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-29',updatedAt:'2026-07-29'},
 {id:'devotional-faithful-in-what-god-has-given-you',type:'Devotional',title:'Faithful in What God Has Given You',description:'Our responsibilities at home and work are opportunities to serve God. Faithfulness in ordinary things reveals our character and reflects Christ to those around us.',url:'devotional.html?id=faithful-in-what-god-has-given-you',category:'Responsibility',series:'Brotherhood Devotionals',scripture:['Colossians 3:23-24'],book:'Colossians',topics:['responsibility','faithfulness','family','work','integrity','service','dependability'],audience:['Men','Families','Workers','Small Groups','Individuals'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'},
 {id:'devotional-faith-for-the-next-decision',type:'Devotional',title:'Faith for the Next Decision',description:'Difficult decisions do not have to be made in fear. God invites us to seek His wisdom, listen for His direction, and trust Him with the outcome.',url:'devotional.html?id=faith-for-the-next-decision',category:'Wisdom and Discernment',series:'Brotherhood Devotionals',scripture:['James 1:5'],book:'James',topics:['wisdom','discernment','decisions','prayer','counsel','faith','fear'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'},
 {id:'devotional-growing-into-the-leader-god-is-forming',type:'Devotional',title:'Growing Into the Leader God Is Forming',description:'Spiritual leadership requires reflection, intentional growth, and goals that honor God. We move forward by learning from the past and remaining focused on His calling.',url:'devotional.html?id=growing-into-the-leader-god-is-forming',category:'Spiritual Growth',series:'Brotherhood Devotionals',scripture:['Philippians 3:13-14'],book:'Philippians',topics:['spiritual growth','leadership','goals','accountability','calling','reflection','discipline'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'}
];
const existing=new Set(window.NLDG_LIBRARY.map(item=>item.id));
window.NLDG_LIBRARY.push(...items.filter(item=>!existing.has(item.id)));
window.NLDG_STUDIES=window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT=window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_DEVOTIONAL_LIBRARY_LOADED=true;
})();
