(()=>{
if(window.NLDG_DEVOTIONAL_LIBRARY_LOADED||!window.NLDG_LIBRARY)return;
const items=[
 {id:'devotional-you-are-known',type:'Devotional',title:'You Are Known',description:'Before the world formed an opinion about you, God already knew you and created you with purpose.',url:'devotionals/you-are-known.html',category:'Identity',series:'No Labels Devotionals',scripture:['Psalm 139:13-14'],book:'Psalms',topics:['identity','known by God','purpose','worth'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:5,featured:true,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-not-your-past',type:'Devotional',title:'You Are Not Your Past',description:'In Christ, your story is still being written. Grace gives room to grow without denying where you have been.',url:'devotionals/not-your-past.html',category:'Grace',series:'No Labels Devotionals',scripture:['2 Corinthians 5:17'],book:'2 Corinthians',topics:['grace','new creation','past','growth'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-you-are-held',type:'Devotional',title:'You Are Held',description:'Circumstances may change quickly, but the love of God remains steady.',url:'devotionals/you-are-held.html',category:'Hope',series:'No Labels Devotionals',scripture:['Romans 8:38-39'],book:'Romans',topics:['hope','love of God','uncertainty','security'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-created-for-good-works',type:'Devotional',title:'Created for Good Works',description:'Purpose begins with the God who designed you and continues through faithful obedience.',url:'devotionals/created-for-good-works.html',category:'Purpose',series:'No Labels Devotionals',scripture:['Ephesians 2:10'],book:'Ephesians',topics:['purpose','service','obedience','good works'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-more-than-a-label',type:'Devotional',title:'You Are More Than a Label',description:'Labels may describe an experience, but they cannot measure your God-given worth.',url:'devotionals/more-than-a-label.html',category:'Identity',series:'No Labels Devotionals',scripture:['Genesis 1:27'],book:'Genesis',topics:['identity','image of God','dignity','worth','labels'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-peace-is-a-practice',type:'Devotional',title:'Peace Is a Practice',description:'Peacemaking requires courage, patience, truth, and love.',url:'devotionals/peace-is-a-practice.html',category:'Spiritual Growth',series:'No Labels Devotionals',scripture:['Matthew 5:9'],book:'Matthew',topics:['peace','peacemaking','conflict','courage','love'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:7,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-hope-that-holds',type:'Devotional',title:'Hope That Holds',description:'Biblical hope is a confident expectation rooted in God’s promises.',url:'devotionals/hope-that-holds.html',category:'Hope',series:'No Labels Devotionals',scripture:['Romans 15:13'],book:'Romans',topics:['hope','joy','peace','trust','Holy Spirit'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-when-god-feels-silent',type:'Devotional',title:'When God Feels Silent',description:'There are seasons when God seems silent, but His silence is never His absence. Learn to trust His faithfulness even when you cannot hear His voice.',url:'devotionals/when-god-feels-silent.html',category:'Faith',series:'No Labels Devotionals',scripture:['Psalm 13:1-6','Psalm 13:5-6'],book:'Psalms',topics:['faith','waiting','unanswered prayer','God’s presence','trust','lament','unfailing love'],audience:['Individuals','Families','Small Groups'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-28',updatedAt:'2026-07-30'},
 {id:'devotional-the-courage-to-lead',type:'Devotional',title:'The Courage to Lead',description:'Godly leadership does not require us to be fearless. It requires us to trust that God is with us and move forward with courage, integrity, and faith.',url:'devotionals/the-courage-to-lead.html',category:'Godly Leadership',series:'Brotherhood Devotionals',scripture:['Joshua 1:9'],book:'Joshua',topics:['leadership','courage','faith','integrity','character','service','fear'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-29',updatedAt:'2026-07-29'},
 {id:'devotional-faithful-in-what-god-has-given-you',type:'Devotional',title:'Faithful in What God Has Given You',description:'Our responsibilities at home and work are opportunities to serve God. Faithfulness in ordinary things reveals our character and reflects Christ to those around us.',url:'devotionals/faithful-in-what-god-has-given-you.html',category:'Responsibility',series:'Brotherhood Devotionals',scripture:['Colossians 3:23-24'],book:'Colossians',topics:['responsibility','faithfulness','family','work','integrity','service','dependability'],audience:['Men','Families','Workers','Small Groups','Individuals'],difficulty:'All Levels',duration:5,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'},
 {id:'devotional-faith-for-the-next-decision',type:'Devotional',title:'Faith for the Next Decision',description:'Difficult decisions do not have to be made in fear. God invites us to seek His wisdom, listen for His direction, and trust Him with the outcome.',url:'devotionals/faith-for-the-next-decision.html',category:'Wisdom and Discernment',series:'Brotherhood Devotionals',scripture:['James 1:5'],book:'James',topics:['wisdom','discernment','decisions','prayer','counsel','faith','fear'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'},
 {id:'devotional-growing-into-the-leader-god-is-forming',type:'Devotional',title:'Growing Into the Leader God Is Forming',description:'Spiritual leadership requires reflection, intentional growth, and goals that honor God. We move forward by learning from the past and remaining focused on His calling.',url:'devotionals/growing-into-the-leader-god-is-forming.html',category:'Spiritual Growth',series:'Brotherhood Devotionals',scripture:['Philippians 3:13-14'],book:'Philippians',topics:['spiritual growth','leadership','goals','accountability','calling','reflection','discipline'],audience:['Men','Leaders','Small Groups','Individuals'],difficulty:'All Levels',duration:6,featured:false,status:'published',publishedAt:'2026-07-30',updatedAt:'2026-07-30'}
];
const existing=new Set(window.NLDG_LIBRARY.map(item=>item.id));
window.NLDG_LIBRARY.push(...items.filter(item=>!existing.has(item.id)));
window.NLDG_STUDIES=window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT=window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_DEVOTIONAL_LIBRARY_LOADED=true;
})();
