(()=>{
const studies=window.HOMBRES_DE_FE_STUDIES||[];
const params=new URLSearchParams(location.search);
let number=Number(params.get('study'));
if(!Number.isInteger(number)||number<1||number>10)number=0;
const progressKey='nldg-hombres-de-fe-progress';
const completed=JSON.parse(localStorage.getItem(progressKey)||'[]');
const root=document.getElementById('hombresDeFeRoot');
function languageSwitch(englishHref){return `<div class="actions mof-language-switch"><a class="button secondary" href="${englishHref}">English</a><a class="button primary" href="${number?`hombres-de-fe.html?study=${number}`:'hombres-de-fe.html'}" aria-current="page">Español</a></div>`}
function studyHref(n){return `hombres-de-fe.html?study=${n}`}
function renderLanding(){
 document.documentElement.lang='es';
 document.title='Hombres de Fe | No Labels, Designed by God';
 const count=completed.filter(n=>n>=1&&n<=10).length;
 root.innerHTML=`
 <section class="mof-hero">
  <div><p class="kicker">Hombres de Fe</p><h1>Conocidos por Dios. <span>Formados por Cristo.</span> Caminando como hermanos.</h1><p class="lead">Un camino de discipulado centrado en la Escritura para hombres que buscan identidad más allá del rendimiento, libertad del pecado, integridad en lo privado, fortaleza honesta, liderazgo de servicio, relaciones saludables, mayordomía fiel y el valor de ayudar a otro hombre a crecer.</p>${languageSwitch('men-of-faith.html')}<div class="actions"><a class="button primary" href="${studyHref(1)}">Comenzar el Camino</a><a class="button secondary" href="#camino">Ver los Diez Estudios</a></div></div>
  <div class="mof-hero-card"><span>Camino completo de diez estudios</span><strong>Los hombres fieles se forman, no se fabrican.</strong><p>Este camino no mide la hombría por ingresos, personalidad, fuerza física, matrimonio, paternidad, liderazgo público o silencio emocional. Comienza con pertenecer a Cristo y crece mediante verdad, gracia, responsabilidad, comunidad y servicio.</p><div class="mof-scripture"><p>“Somos hechura de Dios, creados en Cristo Jesús para buenas obras.”</p><strong>Efesios 2:10</strong></div></div>
 </section>
 <section class="section mof-foundation"><div class="mof-foundation-copy"><p class="kicker">El fundamento</p><h2>El valor de un hombre se recibe de Dios antes de expresarse mediante trabajo, liderazgo o responsabilidad.</h2><p>Los hombres muchas veces aprenden a medirse por lo que producen, proveen, arreglan, soportan, ganan, lideran o controlan. Esas responsabilidades pueden importar, pero ninguna puede cargar todo el peso de la identidad.</p><p>Hombres de Fe invita a seguir a Jesús sin fingir, rendir espectáculo, dominar, retirarse o caminar solos. Hace espacio para fortaleza y ternura, convicción y arrepentimiento, valor y duelo, responsabilidad y descanso.</p></div><div class="mof-label-cloud" aria-label="Roles y expectativas que un hombre puede llevar"><span>Esposo</span><span>Soltero</span><span>Padre</span><span>Hijo</span><span>Hermano</span><span>Líder</span><span>Trabajador</span><span>Proveedor</span><span>Cuidador</span><span>Mentor</span><span>Fuerte</span><span>Luchando</span><span>Conocido y llamado por Dios</span></div></section>
 <section class="section"><div class="section-heading"><p class="kicker">Cómo enseña este camino</p><h2>Verdad, gracia, responsabilidad y hermandad.</h2><p>Cada estudio comienza con la Escritura y rechaza tanto estereotipos superficiales como excusas para conducta dañina.</p></div><div class="mof-principles"><article><strong>La Escritura primero</strong><p>Cultura, expectativas familiares y experiencia personal se examinan a la luz del texto bíblico.</p></article><article><strong>Identidad en Cristo</strong><p>El valor no depende de ingresos, estatus, fuerza, matrimonio, paternidad, logros o aprobación.</p></article><article><strong>Fe honesta</strong><p>Los hombres pueden nombrar miedo, duelo, debilidad, tentación, duda y necesidad sin vergüenza.</p></article><article><strong>Responsabilidad de servicio</strong><p>El liderazgo protege, escucha, sirve, dice verdad, acepta corrección y rechaza control.</p></article><article><strong>Hermandad fiel</strong><p>Los hombres saludables animan, desafían, restauran y apoyan sin secreto ni dominación.</p></article></div></section>
 <div class="path-progress" aria-live="polite"><div class="path-progress-top"><strong>Tu progreso: ${count} de 10 estudios</strong><span>El progreso y las notas en español se guardan por separado en este dispositivo.</span></div><div class="path-progress-track"><i style="width:${count*10}%"></i></div></div>
 <section id="camino" class="section"><div class="section-heading"><p class="kicker">Camino completo de diez estudios</p><h2>De identidad y libertad hacia una vida que fortalece a otros.</h2><p>Puedes seguirlos en orden o regresar al área donde necesites crecer.</p></div><div class="mof-journey-grid">${studies.map(s=>`<article class="mof-study-card available ${completed.includes(s.number)?'complete':''}"><span class="mof-study-number">${s.number}</span><div><h3>${s.title}</h3><p>${s.truth}</p><small>${s.main}</small><a href="${studyHref(s.number)}">${completed.includes(s.number)?'Revisar Estudio ✓':'Abrir Estudio →'}</a></div></article>`).join('')}</div></section>
 <section class="section mof-care"><div><p class="kicker">Seguridad y cuidado</p><h2>La responsabilidad nunca debe convertirse en control, secreto o cuidado de crisis improvisado.</h2><p>El ministerio de hombres debe fomentar honestidad respetando privacidad, explicando límites de confidencialidad y buscando apoyo calificado cuando un asunto supera el rol del líder.</p></div><div><ul><li>Peligro inmediato, abuso, amenazas o autolesión requieren acción apropiada para la seguridad.</li><li>Adicción, trauma, angustia severa y conducta compulsiva pueden requerir atención profesional.</li><li>Los líderes no deben investigar acusaciones graves ni prometer secreto absoluto.</li><li>Matrimonio, paternidad, ingresos y liderazgo público no miden el valor espiritual.</li><li>El arrepentimiento debe incluir verdad, responsabilidad, reparación y cambio de conducta.</li></ul></div></section>`;
}
function renderStudy(item){
 document.documentElement.lang='es';
 document.title=`${item.title} | Hombres de Fe`;
 const noteKey=`nldg-hombres-de-fe-notes-${item.number}`;
 const isDone=completed.includes(item.number);
 root.innerHTML=`
 <section class="mof-study-hero page-hero"><p class="study-label">Hombres de Fe • Estudio ${item.number} de 10</p><h1>${item.title}</h1><p class="lead">${item.truth}</p><div class="mof-study-meta"><span>📖 ${item.main}</span><span>Apoyo: ${item.supporting}</span><span>${item.minutes}</span><span>${item.theme}</span></div>${languageSwitch(item.english)}</section>
 <div class="mof-study-layout"><article class="mof-study-content">
 <section class="mof-block mof-highlight"><h2>Verdad bíblica central</h2><p><strong>${item.truth}</strong></p></section>
 <section class="mof-block"><h2>Enfoque de la Escritura</h2><p>Lee <strong>${item.main}</strong>. Luego considera los pasajes de apoyo: <strong>${item.supporting}</strong>. Comienza con lo que el texto dice antes de llevar tu experiencia al pasaje.</p></section>
 <section class="mof-block mof-context"><h2>Contexto en lenguaje sencillo</h2>${item.context.map(p=>`<p>${p}</p>`).join('')}</section>
 ${item.movements.map(m=>`<section class="mof-block"><h2>${m[0]}</h2><p>${m[1]}</p></section>`).join('')}
 <section class="mof-block mof-jesus-connection"><h2>Conexión con Jesús</h2><p>${item.jesus}</p><h3>No confundas estas cosas</h3><ul>${item.distinctions.map(d=>`<li>${d}</li>`).join('')}</ul></section>
 ${item.rhythm?`<section class="mof-block"><h2>Un ritmo sencillo de mentoría</h2><ol>${item.rhythm.map(r=>`<li>${r}</li>`).join('')}</ol></section>`:''}
 <section class="mof-block"><h2>Preguntas para conversar</h2><ol>${item.questions.map(q=>`<li>${q}</li>`).join('')}</ol></section>
 <section class="mof-block"><h2>Vívelo esta semana</h2><p>${item.live}</p></section>
 <section class="mof-block mof-prayer"><h2>Oración</h2><p>${item.prayer}</p></section>
 <section class="mof-block"><h2>Nota para líderes y mentores</h2><p>${item.leader}</p></section>
 <section class="mof-block"><h2>Mi respuesta</h2><p>Escribe una oración, pregunta, verdad bíblica o próximo paso. Tus notas permanecen en este dispositivo.</p><textarea id="hombresNotes" class="lesson-notes" rows="7" placeholder="¿Qué está mostrando Dios por medio de Su Palabra?"></textarea><div class="actions"><button id="saveHombresNotes" class="button secondary" type="button">Guardar Notas</button><button id="completeHombresStudy" class="button primary" type="button">${isDone?'Estudio completado ✓':`Marcar Estudio ${item.number} como Completado`}</button></div><p id="hombresStatus" class="lesson-status"></p></section>
 <div class="lesson-actions mof-actions"><a class="button secondary" href="${item.number>1?studyHref(item.number-1):'hombres-de-fe.html'}">← ${item.number>1?'Estudio anterior':'Hombres de Fe'}</a><button class="button secondary" type="button" onclick="window.print()">Imprimir Estudio</button><a class="button primary" href="${item.number<10?studyHref(item.number+1):'hombres-de-fe.html'}">${item.number<10?'Próximo Estudio →':'Volver al Camino →'}</a></div>
 </article><aside class="mof-study-side"><div class="mof-side-card"><strong>Propósito del estudio</strong><p>${item.truth}</p></div><div class="mof-side-card"><strong>Enfoque Escritura primero</strong><p>Lee el pasaje en contexto. Distingue lo que la Escritura dice claramente de interpretación, tradición y aplicación.</p></div><div class="mof-side-card"><strong>Límites saludables</strong><p>No presiones revelaciones privadas. Asuntos de abuso, peligro, trauma, adicción, autolesión, conducta ilegal o crisis pueden requerir apoyo calificado y reportes apropiados.</p></div></aside></div>`;
 const textarea=document.getElementById('hombresNotes');textarea.value=localStorage.getItem(noteKey)||'';
 document.getElementById('saveHombresNotes').onclick=()=>{localStorage.setItem(noteKey,textarea.value);const s=document.getElementById('hombresStatus');s.textContent='Notas guardadas en este dispositivo.';setTimeout(()=>s.textContent='',2200)};
 document.getElementById('completeHombresStudy').onclick=()=>{let saved=JSON.parse(localStorage.getItem(progressKey)||'[]');if(!saved.includes(item.number))saved.push(item.number);saved.sort((a,b)=>a-b);localStorage.setItem(progressKey,JSON.stringify(saved));document.getElementById('completeHombresStudy').textContent='Estudio completado ✓';document.getElementById('hombresStatus').textContent=item.number===10?'Completaste los diez estudios de Hombres de Fe. Sigue creciendo en Cristo y fortaleciendo a otros.':'Tu progreso en español está guardado.';};
}
if(number){const item=studies.find(s=>s.number===number);item?renderStudy(item):renderLanding();}else renderLanding();
setTimeout(()=>window.NLDG_SCRIPTURE_LINKS?.linkReferences?.(root),0);
})();