(function(){
const STUDIES='nldg-ministry-assistant-sessions-v7',GOALS='nldg-journey-goals-v1',REFLECTIONS='nldg-journey-reflections-v1',MEMORY='nldg-journey-memory-v1',PRAYERS='nldg-prayers-v1';
const read=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const studies=()=>read(STUDIES,[]),goals=()=>read(GOALS,[]),reflections=()=>read(REFLECTIONS,[]),memory=()=>read(MEMORY,[]),prayers=()=>read(PRAYERS,[]);
const studyById=(id,list=studies())=>list.find(x=>x.id===id);
function studyName(id,list){const s=studyById(id,list);return s?(s.title||s.study?.ref||'Saved study'):''}
function renderStudyLinks(list){document.querySelectorAll('.journey-study-link').forEach(select=>{const value=select.value;select.innerHTML='<option value="">Link to a saved study (optional)</option>'+list.map(s=>`<option value="${esc(s.id)}">${esc(s.title||s.study?.ref||'Saved study')}</option>`).join('');select.value=value})}
function render(){
 const s=studies(),g=goals(),r=reflections(),m=memory(),p=prayers(),recent=s.slice().sort((a,b)=>new Date(b.updated||b.created)-new Date(a.updated||a.created))[0],active=p.filter(x=>!x.answered),answered=p.filter(x=>x.answered);
 renderStudyLinks(s);
 document.querySelector('#journey-continue').innerHTML=recent?`<span>Continue your journey</span><h3>${esc(recent.title||recent.study?.ref||'Bible study')}</h3><p>${esc(recent.study?.ref||'Saved study')}</p><a class="button primary" href="study-library.html">Continue Study</a>`:`<span>Continue your journey</span><h3>Start a Bible study</h3><p>Your latest study will appear here.</p><a class="button primary" href="ministry-assistant.html">Open Bible Study</a>`;
 document.querySelector('#journey-prayer').innerHTML=`<span>Prayer focus</span><h3>${active.length} active request${active.length===1?'':'s'}</h3><p>${active[0]?esc(active[0].title):'Bring a concern before God and record it in your journal.'}</p><a class="button secondary" href="#prayer-form">Open Prayer Journal</a>`;
 document.querySelector('#journey-goal').innerHTML=`<span>Current goals</span><h3>${g.filter(x=>!x.complete).length} in progress</h3><p>Keep moving in steady, faithful steps.</p><a class="button secondary" href="#goal-form">Add a Goal</a>`;
 document.querySelector('#journey-memory').innerHTML=`<span>Scripture memory</span><h3>${m.length} verse${m.length===1?'':'s'}</h3><p>${m[0]?esc(m[0].reference):'Add a verse you want to carry with you.'}</p><a class="button secondary" href="#memory-form">Review Verses</a>`;
 renderGoals(g,s);renderReflections(r,s);renderMemory(m);renderTestimonies(answered,s);renderTimeline(s,g,r,m,p)
}
function linkedStudy(id,list){const name=studyName(id,list);return name?`<p class="journey-linked">Linked study: ${esc(name)}</p>`:''}
function renderGoals(list,s){document.querySelector('#journey-goals').innerHTML=list.length?list.map(x=>`<article><small>${esc(x.category)}</small><h3>${esc(x.title)}</h3>${linkedStudy(x.studyId,s)}<div class="journey-progress"><span style="width:${Math.max(0,Math.min(100,x.progress||0))}%"></span></div><p>${x.progress||0}% complete</p><div class="journey-actions"><button data-goal-progress="${x.id}">Update progress</button><button data-goal-complete="${x.id}">${x.complete?'Reopen':'Complete'}</button><button data-goal-delete="${x.id}">Delete</button></div></article>`).join(''):'<p class="journey-empty">No goals yet.</p>'}
function renderReflections(list,s){document.querySelector('#journey-reflections').innerHTML=list.length?list.slice(0,8).map(x=>`<article><small>${new Date(x.created).toLocaleDateString()}</small><h3>${esc(x.title)}</h3>${linkedStudy(x.studyId,s)}<p>${esc(x.learned)}</p>${x.response?`<p><strong>Response:</strong> ${esc(x.response)}</p>`:''}<div class="journey-actions"><button data-reflection-delete="${x.id}">Delete</button></div></article>`).join(''):'<p class="journey-empty">Your reflections will appear here.</p>'}
function renderMemory(list){document.querySelector('#journey-memory-list').innerHTML=list.length?list.map(x=>`<article><small>${esc(x.translation||'')}</small><h3>${esc(x.reference)}</h3><p>${esc(x.text)}</p><p>Confidence: ${x.confidence||1}/5${x.lastReviewed?` · Reviewed ${new Date(x.lastReviewed).toLocaleDateString()}`:''}</p><div class="journey-actions"><button data-memory-review="${x.id}">Review</button><button data-memory-reset="${x.id}">Reset confidence</button><button data-memory-delete="${x.id}">Delete</button></div></article>`).join(''):'<p class="journey-empty">No memory verses yet.</p>'}
function renderTestimonies(list,s){document.querySelector('#journey-testimonies').innerHTML=list.length?list.sort((a,b)=>(b.answeredAt||0)-(a.answeredAt||0)).map(x=>`<article><small>${esc(x.category||'Prayer')} · Answered ${new Date(x.answeredAt||x.createdAt).toLocaleDateString()}</small><h3>${esc(x.title)}</h3>${x.details?`<p>${esc(x.details)}</p>`:''}${x.scripture?`<p><strong>Scripture:</strong> ${esc(x.scripture)}</p>`:''}${linkedStudy(x.studyId,s)}<div class="journey-actions"><button data-prayer-reopen="${x.id}">Mark Active</button></div></article>`).join(''):'<p class="journey-empty">Answered prayers will appear here as testimonies.</p>'}
function renderTimeline(s,g,r,m,p){const items=[...s.map(x=>({date:x.updated||x.created,title:x.title||x.study?.ref||'Bible study',type:'Study'})),...g.map(x=>({date:x.updated||x.created,title:x.title,type:x.complete?'Goal completed':'Goal'})),...r.map(x=>({date:x.created,title:x.title,type:'Reflection'})),...m.map(x=>({date:x.lastReviewed||x.created,title:x.reference,type:x.lastReviewed?'Scripture reviewed':'Memory verse'})),...p.map(x=>({date:x.answeredAt||x.createdAt,title:x.title,type:x.answered?'Answered prayer':'Prayer'}))].filter(x=>x.date).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,16);document.querySelector('#journey-timeline').innerHTML=items.length?items.map(x=>`<article class="timeline-entry"><small>${esc(x.type)} · ${new Date(x.date).toLocaleDateString()}</small><h3>${esc(x.title)}</h3></article>`).join(''):'<p class="journey-empty">Your journey timeline will grow as you study, pray, reflect, and set goals.</p>'}
document.querySelector('#goal-form')?.addEventListener('submit',e=>{e.preventDefault();const list=goals();list.unshift({id:crypto.randomUUID(),title:e.target.title.value.trim(),category:e.target.category.value,studyId:e.target.studyId.value,progress:Number(e.target.progress.value)||0,complete:false,created:new Date().toISOString(),updated:new Date().toISOString()});write(GOALS,list);e.target.reset();render()});
document.querySelector('#reflection-form')?.addEventListener('submit',e=>{e.preventDefault();const list=reflections();list.unshift({id:crypto.randomUUID(),title:e.target.title.value.trim(),studyId:e.target.studyId.value,learned:e.target.learned.value.trim(),response:e.target.response.value.trim(),created:new Date().toISOString()});write(REFLECTIONS,list);e.target.reset();render()});
document.querySelector('#memory-form')?.addEventListener('submit',e=>{e.preventDefault();const list=memory();list.unshift({id:crypto.randomUUID(),reference:e.target.reference.value.trim(),text:e.target.text.value.trim(),translation:e.target.translation.value,confidence:1,created:new Date().toISOString(),lastReviewed:null});write(MEMORY,list);e.target.reset();render()});
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.goalProgress){const list=goals(),x=list.find(v=>v.id===t.dataset.goalProgress),p=prompt('Progress percentage:',x.progress||0);if(p!==null){x.progress=Math.max(0,Math.min(100,Number(p)||0));x.complete=x.progress===100;x.updated=new Date().toISOString();write(GOALS,list);render()}}if(t.dataset.goalComplete){const list=goals(),x=list.find(v=>v.id===t.dataset.goalComplete);x.complete=!x.complete;x.progress=x.complete?100:Math.min(x.progress||0,99);x.updated=new Date().toISOString();write(GOALS,list);render()}if(t.dataset.goalDelete){write(GOALS,goals().filter(x=>x.id!==t.dataset.goalDelete));render()}if(t.dataset.reflectionDelete){write(REFLECTIONS,reflections().filter(x=>x.id!==t.dataset.reflectionDelete));render()}if(t.dataset.memoryReview){const list=memory(),x=list.find(v=>v.id===t.dataset.memoryReview);x.lastReviewed=new Date().toISOString();x.confidence=Math.min(5,(x.confidence||1)+1);write(MEMORY,list);render()}if(t.dataset.memoryReset){const list=memory(),x=list.find(v=>v.id===t.dataset.memoryReset);x.confidence=1;x.lastReviewed=null;write(MEMORY,list);render()}if(t.dataset.memoryDelete){write(MEMORY,memory().filter(x=>x.id!==t.dataset.memoryDelete));render()}if(t.dataset.prayerReopen&&window.NLDG_PERSONAL){window.NLDG_PERSONAL.togglePrayer(t.dataset.prayerReopen);render()}});
document.addEventListener('nldg:prayers-changed',render);render()
})();