(()=>{
if(window.NLDG_LEADERSHIP_LIBRARY_LOADED||!window.NLDG_LIBRARY)return;
const base={category:'Leadership',series:'Leadership',difficulty:'All Levels',duration:60,status:'published',publishedAt:'2026-07-29',updatedAt:'2026-07-29'};
const items=[
{id:'leadership',type:'Study Collection',title:'Leadership',description:'Called by God. Formed in character. Leading through service, wisdom, healthy teams, accountability, endurance, and multiplication.',url:'leadership.html',scripture:['Mark 10:43-45','1 Peter 5:1-5'],book:'Various',topics:['leadership','character','service','accountability','teams','mentoring'],audience:['Pastors','Teachers','Mentors','Ministry Teams','Emerging Leaders'],featured:true,...base},
{id:'leadership-called-before-positioned',type:'Study',title:'Called Before Positioned',description:'Ground leadership in belonging to Christ, faithful presence, calling, and stewardship rather than title or visibility.',url:'leadership-study.html?study=1',scripture:['Mark 3:13-15','John 15:1-8','Exodus 3:1-12'],book:'Various',topics:['calling','identity','stewardship','faithfulness'],audience:['Emerging Leaders','Volunteers','Mentors','Ministry Teams'],...base},
{id:'leadership-character-before-influence',type:'Study',title:'Character Before Influence',description:'Place integrity, repentance, accountability, self-control, and the fruit of the Spirit before talent or platform.',url:'leadership-study.html?study=2',scripture:['1 Timothy 3:1-13','Galatians 5:22-25','Titus 1:5-9'],book:'Various',topics:['character','integrity','repentance','accountability'],audience:['Pastors','Teachers','Mentors','Emerging Leaders'],...base},
{id:'leadership-leading-like-jesus',type:'Study',title:'Leading Like Jesus',description:'Exercise authority through service, courage, truth, protection, sacrifice, and the equipping of others.',url:'leadership-study.html?study=3',scripture:['Mark 10:35-45','John 13:1-17','Philippians 2:3-11'],book:'Various',topics:['servant leadership','authority','service','Jesus'],audience:['Pastors','Ministry Teams','Mentors','Volunteers'],...base},
{id:'leadership-wisdom-decisions',type:'Study',title:'Wisdom, Decisions, and Discernment',description:'Make decisions through Scripture, prayer, counsel, truthful facts, affected voices, and humble review.',url:'leadership-study.html?study=4',scripture:['James 1:5-8','Acts 15:1-29','Proverbs 11:14'],book:'Various',topics:['wisdom','discernment','decisions','counsel'],audience:['Pastors','Boards','Ministry Teams','Emerging Leaders'],...base},
{id:'leadership-teaching-scripture',type:'Study',title:'Teaching Scripture Faithfully',description:'Handle Scripture with context, clarity, humility, preparation, responsible application, and accountability.',url:'leadership-study.html?study=5',scripture:['2 Timothy 2:14-17','Nehemiah 8:1-12','James 3:1'],book:'Various',topics:['teaching','Scripture','interpretation','application'],audience:['Teachers','Pastors','Small Group Leaders','Mentors'],...base},
{id:'leadership-building-teams',type:'Study',title:'Building Healthy Teams',description:'Share mission, develop gifts, delegate responsibly, communicate clearly, and create room for honest feedback.',url:'leadership-study.html?study=6',scripture:['1 Corinthians 12:4-27','Ephesians 4:11-16','Exodus 18:13-27'],book:'Various',topics:['teams','gifts','delegation','communication'],audience:['Ministry Teams','Pastors','Administrators','Volunteers'],...base},
{id:'leadership-conflict-correction',type:'Study',title:'Conflict, Correction, and Reconciliation',description:'Address conflict through listening, truth, repair, due process, boundaries, and protection for vulnerable people.',url:'leadership-study.html?study=7',scripture:['Matthew 18:15-20','Galatians 6:1-2','Acts 6:1-7'],book:'Various',topics:['conflict','correction','reconciliation','safeguarding'],audience:['Pastors','Boards','Ministry Teams','Mentors'],...base},
{id:'leadership-power-accountability',type:'Study',title:'Power, Accountability, and Boundaries',description:'Name leadership power and place it under transparent systems, shared oversight, ethics, and safeguarding.',url:'leadership-study.html?study=8',scripture:['1 Peter 5:1-5','Ezekiel 34:1-10','2 Corinthians 8:18-21'],book:'Various',topics:['power','accountability','boundaries','ethics','safeguarding'],audience:['Pastors','Boards','Ministry Leaders','Mentors'],...base},
{id:'leadership-change-weariness',type:'Study',title:'Leading Through Change, Pressure, and Weariness',description:'Navigate loss and pressure through honest communication, shared burden, rest, resilience, and qualified support.',url:'leadership-study.html?study=9',scripture:['1 Kings 19:1-18','2 Corinthians 4:7-18','Mark 6:30-32'],book:'Various',topics:['change','burnout','rest','resilience','grief'],audience:['Pastors','Caregivers','Ministry Teams','Leaders'],...base},
{id:'leadership-multiplying-finishing',type:'Study',title:'Multiplying Leaders and Finishing Faithfully',description:'Develop others, share authority, document ministry, plan transitions, and finish each season with integrity.',url:'leadership-study.html?study=10',scripture:['2 Timothy 2:1-7','Acts 20:17-38','Deuteronomy 31:1-8'],book:'Various',topics:['mentoring','succession','legacy','multiplication'],audience:['Pastors','Mentors','Ministry Teams','Emerging Leaders'],...base}
];
const existing=new Set(window.NLDG_LIBRARY.map(item=>item.id));
window.NLDG_LIBRARY.push(...items.filter(item=>!existing.has(item.id)));
window.NLDG_STUDIES=window.NLDG_LIBRARY.filter(item=>item.type==='Study'&&item.status==='published');
window.NLDG_CONTENT=window.NLDG_LIBRARY.filter(item=>item.status==='published');
window.NLDG_LEADERSHIP_LIBRARY_LOADED=true;
})();
