(()=>{
const root=document.getElementById('liderazgoRoot');
const studies=window.NLDG_LIDERAZGO_STUDIES||[];
const params=new URLSearchParams(location.search);
const requested=params.get('study');
const escapeHtml=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const completedKey='nldg-liderazgo-completed-v1';
const notesKey='nldg-liderazgo-notes-v1';
const readJson=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}};
const completed=new Set(readJson(completedKey,[]).map(Number));
const notes=readJson(notesKey,{});
const saveCompleted=()=>localStorage.setItem(completedKey,JSON.stringify([...completed].sort((a,b)=>a-b)));
const saveNotes=()=>localStorage.setItem(notesKey,JSON.stringify(notes));
const languageSwitch=(number=null)=>`<div class="actions"><a class="button secondary" href="${number?`leadership-study.html?study=${number}`:'leadership.html'}">English</a><a class="button primary" href="${number?`liderazgo.html?study=${number}`:'liderazgo.html'}" aria-current="page">Español</a></div>`;
const studyUrl=n=>`liderazgo.html?study=${n}`;
const countLabel=()=>`${completed.size} de 10 estudios marcados como completados`;
function renderHome(){
 document.title='Liderazgo | No Labels, Designed by God';
 root.innerHTML=`
 <section class="ld-hero"><div><p class="kicker">Liderazgo</p><h1>Llamados por Dios. <span>Formados en carácter.</span> Liderando mediante el servicio.</h1><p class="lead">Un camino completo y centrado en la Escritura para pastores, maestros, mentores, equipos ministeriales, voluntarios y líderes emergentes que desean carácter semejante a Cristo, decisiones sabias, equipos saludables, rendición de cuentas, resistencia y multiplicación fiel.</p>${languageSwitch()}<div class="actions"><a class="button primary" href="${studyUrl(1)}">Comenzar el camino</a><a class="button secondary" href="#recorrido">Ver los 10 estudios</a></div></div><div class="ld-hero-card"><span>Camino completo de diez estudios</span><strong>El liderazgo cristiano comienza bajo la autoridad de Jesús.</strong><p>Este camino no mide liderazgo por título, personalidad, plataforma, asistencia o visibilidad. Forma líderes que permanecen en Cristo, sirven a personas, reciben corrección, manejan la Escritura con cuidado, protegen a los vulnerables y equipan a otros.</p><div class="ld-scripture"><p>«El que quiera hacerse grande entre ustedes será su servidor».</p><strong>Marcos 10:43</strong></div></div></section>
 <section class="section ld-foundation"><div><p class="kicker">El fundamento</p><h2>Liderar es mayordomía, no propiedad.</h2><p>Dios confía a líderes personas, verdad, recursos, relaciones, oportunidades e influencia. Nada de eso pertenece al líder.</p><p>Este recorrido coloca carácter antes que carisma, servicio antes que estatus, rendición de cuentas antes que independencia y multiplicación antes que control personal.</p></div><div class="ld-call-cloud"><span>Pastores</span><span>Maestros</span><span>Mentores</span><span>Líderes de grupos</span><span>Equipos ministeriales</span><span>Voluntarios</span><span>Administradores</span><span>Líderes emergentes</span><span>Padres y cuidadores</span><span>Servidores silenciosos</span><span>Mayordomos bajo Cristo</span></div></section>
 <section class="section"><div class="section-heading"><p class="kicker">Cómo enseña este camino</p><h2>Carácter semejante a Cristo, práctica sabia y rendición de cuentas saludable.</h2></div><div class="ld-principles"><article><strong>Jesús en el centro</strong><p>El liderazgo se mide por el carácter y camino de Cristo, no por el poder cultural.</p></article><article><strong>Carácter antes que influencia</strong><p>Don, crecimiento y carisma nunca justifican falta de integridad.</p></article><article><strong>Autoridad que sirve</strong><p>El liderazgo protege, equipa, dice verdad, comparte responsabilidad y rechaza dominación.</p></article><article><strong>Rendición de cuentas y seguridad</strong><p>Sistemas saludables protegen personas, finanzas, información y relaciones ministeriales.</p></article><article><strong>Multiplicación y legado</strong><p>Líderes maduros preparan a otros y liberan responsabilidad significativa.</p></article></div></section>
 <section id="recorrido" class="section"><div class="section-heading"><p class="kicker">Camino completo</p><h2>Los diez estudios están disponibles en español.</h2><p>${countLabel()}</p><progress max="10" value="${completed.size}">${completed.size} de 10</progress></div><div class="ld-journey-grid">${studies.map(s=>`<article class="ld-study-card"><span class="ld-study-number">${s.number}</span><div><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.central)}</p><small>${escapeHtml(s.primary)}</small><a href="${studyUrl(s.number)}">Abrir Estudio ${s.number} →</a>${completed.has(s.number)?'<p><strong>✓ Completado</strong></p>':''}</div></article>`).join('')}</div></section>
 <section class="section ld-safeguard"><div><p class="kicker">Salvaguardas de liderazgo</p><h2>La autoridad espiritual nunca debe usarse para controlar, explotar o silenciar.</h2><p>Abuso, fraude, explotación, acoso, peligro infantil, acecho, amenazas y posibles delitos requieren políticas apropiadas y acción externa calificada cuando corresponda. La restauración a la comunión cristiana no significa automáticamente restauración al liderazgo.</p></div><div><ul><li>Los líderes permanecen bajo Cristo, la Escritura, políticas y supervisión apropiada.</li><li>La reputación institucional nunca debe ponerse por encima de las personas.</li><li>El perdón no borra consecuencias ni demuestra por sí solo idoneidad para liderar.</li><li>La confidencialidad nunca debe esconder peligro o mala conducta seria.</li><li>Asuntos médicos, legales, financieros y de salud mental requieren experiencia calificada.</li></ul></div></section>
 <section class="section ld-safeguard"><div><p class="kicker">Herramientas complementarias</p><h2>El Leadership Toolkit todavía está en inglés.</h2><p>Los diez estudios principales ya están completamente disponibles en español. Las herramientas interactivas de decisiones, equipos, conflicto, rendición de cuentas, desarrollo y transición se traducirán como una capa complementaria posterior.</p><div class="actions"><a class="button secondary" href="leadership-toolkit.html">Abrir Toolkit en inglés</a></div></div></section>`;
}
function renderStudy(study){
 document.title=`${study.title} | Liderazgo`;
 const prev=studies.find(s=>s.number===study.number-1);
 const next=studies.find(s=>s.number===study.number+1);
 root.innerHTML=`
 <section class="ld-study-hero page-hero"><p class="study-label">Liderazgo • Estudio ${study.number} de 10</p><h1>${escapeHtml(study.title)}</h1><p class="lead">${escapeHtml(study.central)}</p><div class="ld-study-meta"><span>📖 ${escapeHtml(study.primary)}</span><span>Apoyo: ${escapeHtml(study.supporting)}</span><span>45–60 minutos</span><span>${escapeHtml(study.theme)}</span></div>${languageSwitch(study.number)}</section>
 <div class="ld-study-layout"><article class="ld-study-content">
 <section class="ld-block ld-highlight"><h2>Verdad bíblica central</h2><p><strong>${escapeHtml(study.central)}</strong></p></section>
 <section class="ld-block"><h2>Introducción</h2>${study.intro.map(p=>`<p>${escapeHtml(p)}</p>`).join('')}</section>
 <section class="ld-block"><h2>Enfoque en la Escritura</h2><p>Lee <strong>${escapeHtml(study.primary)}</strong>. Luego considera los pasajes de apoyo: <strong>${escapeHtml(study.supporting)}</strong>.</p><p>Observa qué revela el texto acerca de Jesús, carácter, autoridad, servicio, responsabilidad, rendición de cuentas, sabiduría y el bien de las personas.</p></section>
 <section class="ld-block"><h2>Contexto en lenguaje sencillo</h2>${study.context.map(p=>`<p>${escapeHtml(p)}</p>`).join('')}</section>
 ${study.movements.map(([title,text])=>`<section class="ld-block"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(text)}</p></section>`).join('')}
 <section class="ld-block ld-highlight"><h2>Conexión con Jesús</h2><p>${escapeHtml(study.jesus)}</p><h3>No confundas estas cosas</h3><ul>${study.distinctions.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section>
 <section class="ld-block"><h2>Preguntas para conversar</h2><ol>${study.questions.map(q=>`<li>${escapeHtml(q)}</li>`).join('')}</ol></section>
 <section class="ld-block"><h2>Pausa y considera</h2><div class="ld-reflection-fields">${study.reflection.map(prompt=>`<label>${escapeHtml(prompt)}<textarea rows="3"></textarea></label>`).join('')}</div></section>
 <section class="ld-block"><h2>Lidera fielmente esta semana</h2>${study.practices.map(p=>`<h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.text)}</p>`).join('')}</section>
 <section class="ld-block ld-prayer"><h2>Oración</h2><p>${escapeHtml(study.prayer)}</p></section>
 <section class="ld-block ld-warning"><h2>Notas para líderes y mentores</h2><p>${escapeHtml(study.leader)}</p><h3>Evita</h3><ul>${study.avoid.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section>
 <section class="ld-block"><h2>Notas privadas</h2><p>Estas notas se guardan solamente en este dispositivo.</p><textarea id="liderazgoNotes" rows="6" style="width:100%">${escapeHtml(notes[study.number]||'')}</textarea><div class="actions"><button class="button secondary" type="button" id="saveLiderazgoNotes">Guardar notas</button></div></section>
 ${study.number===10?'<section class="ld-block ld-highlight"><h2>Camino completado</h2><p>Completar estos diez estudios no significa dominar el liderazgo. Significa comprometerte a seguir liderando bajo Cristo mediante carácter, servicio, Escritura, rendición de cuentas, límites saludables y desarrollo de otros.</p><p>Permanece enseñable, recibe corrección, fortalece salvaguardas y prepara a otros para servir fielmente.</p></section>':''}
 <div class="lesson-actions ld-actions">${prev?`<a class="button secondary" href="${studyUrl(prev.number)}">← Estudio ${prev.number}</a>`:'<a class="button secondary" href="liderazgo.html">← Inicio del recorrido</a>'}<button class="button secondary" type="button" onclick="window.print()">Imprimir estudio</button><button class="button ${completed.has(study.number)?'secondary':'primary'}" type="button" id="toggleLiderazgoComplete">${completed.has(study.number)?'✓ Marcado como completado':'Marcar como completado'}</button>${next?`<a class="button primary" href="${studyUrl(next.number)}">Siguiente estudio →</a>`:'<a class="button primary" href="liderazgo.html">Centro de Liderazgo</a>'}</div>
 </article><aside class="ld-study-side"><div class="ld-side-card"><strong>Propósito del estudio</strong><p>${escapeHtml(study.central)}</p></div><div class="ld-side-card"><strong>Úsalo para</strong><ul><li>Formación personal</li><li>Equipos de liderazgo</li><li>Mentoría</li><li>Clases y retiros</li></ul></div><div class="ld-side-card"><strong>Postura de liderazgo</strong><p>Permanece bajo Cristo, recibe verdad, protege personas, comparte responsabilidad y rechaza secreto o dominación.</p></div><div class="ld-side-card"><strong>${next?'Siguiente en el camino':'Continúa creciendo'}</strong><p>${next?`Estudio ${next.number}: ${escapeHtml(next.title)}`:'Continúa en Escritura, rendición de cuentas, comunidad saludable y desarrollo de otros.'}</p></div></aside></div>`;
 const notesArea=document.getElementById('liderazgoNotes');
 document.getElementById('saveLiderazgoNotes')?.addEventListener('click',()=>{notes[study.number]=notesArea.value;saveNotes();});
 document.getElementById('toggleLiderazgoComplete')?.addEventListener('click',()=>{completed.has(study.number)?completed.delete(study.number):completed.add(study.number);saveCompleted();renderStudy(study);});
}
const number=Number(requested);
const study=Number.isFinite(number)?studies.find(s=>s.number===number):null;
if(requested&&study)renderStudy(study);else renderHome();
})();