(()=>{
const studies=window.MATRIMONIO_FAMILIA_STUDIES||[];
const params=new URLSearchParams(location.search);
let number=Number(params.get('study'));
if(!Number.isInteger(number)||number<1||number>10)number=0;
const progressKey='nldg-matrimonio-familia-progress';
const completed=JSON.parse(localStorage.getItem(progressKey)||'[]');
const root=document.getElementById('matrimonioFamiliaRoot');
function studyHref(n){return `matrimonio-familia.html?study=${n}`}
function languageSwitch(englishHref){return `<div class="actions mf-language-switch"><a class="button secondary" href="${englishHref}">English</a><a class="button primary" href="${number?studyHref(number):'matrimonio-familia.html'}" aria-current="page">Español</a></div>`}
function renderLanding(){
 document.documentElement.lang='es';
 document.title='Matrimonio y Familia | No Labels, Designed by God';
 const count=completed.filter(n=>n>=1&&n<=10).length;
 root.innerHTML=`
 <section class="mf-hero"><div><p class="kicker">Matrimonio y Familia</p><h1>Arraigados en Cristo. <span>Creciendo en amor.</span> Bendiciendo a otros.</h1><p class="lead">Un camino de discipulado centrado en la Escritura para matrimonios, padres, adultos solteros, familias ensambladas, cuidadores y hogares que buscan comunicación más saludable, relaciones fieles, sabiduría práctica y una vida compartida formada por Jesús.</p>${languageSwitch('marriage-family.html')}<div class="actions"><a class="button primary" href="${studyHref(1)}">Comenzar el Camino</a><a class="button secondary" href="#camino">Ver los Diez Estudios</a></div></div><div class="mf-hero-card"><span>Camino completo de diez estudios</span><strong>Los hogares saludables se forman con gracia y verdad.</strong><p>Este camino no presenta una estructura familiar, temporada o personalidad como el estándar para todos. Ayuda a los hogares a seguir a Jesús mediante amor, honestidad, responsabilidad, límites, arrepentimiento, pertenencia y servicio.</p><div class="mf-scripture"><p>“Y sobre todas estas cosas vestíos de amor, que es el vínculo perfecto.”</p><strong>Colosenses 3:14</strong></div></div></section>
 <section class="section mf-foundation"><div class="mf-foundation-copy"><p class="kicker">El fundamento</p><h2>Los roles familiares importan, pero la identidad y el valor comienzan en Cristo.</h2><p>La vida familiar puede incluir alegría, responsabilidad, duelo, conflicto, transición y amor profundo. Algunos hogares incluyen hijos; otros incluyen una pareja, una persona, familiares extendidos, amistades, cuidadores o relaciones reconstruidas después de pérdidas.</p><p>Este camino enseña convicciones bíblicas sin idealizar una sola forma de hogar ni esconder el daño. Hace espacio para soltería, matrimonio, crianza, infertilidad, divorcio, viudez, adopción, cuidado de otros, familias ensambladas y temporadas cambiantes.</p></div><div class="mf-label-cloud"><span>Soltero/a</span><span>Casado/a</span><span>Padre/Madre</span><span>Sin hijos</span><span>Ensamblada</span><span>Viudo/a</span><span>Divorciado/a</span><span>Cuidador/a</span><span>Abuelo/a</span><span>Adoptiva</span><span>Familia extendida</span><span>Perteneciendo a Cristo</span></div></section>
 <section class="section"><div class="section-heading"><p class="kicker">Cómo enseña este camino</p><h2>Escritura, dignidad, responsabilidad y seguridad.</h2><p>Cada estudio une verdad bíblica con discipulado práctico y cuidado claro para personas en situaciones difíciles o inseguras.</p></div><div class="mf-principles"><article><strong>La Escritura primero</strong><p>Tradiciones familiares y expectativas culturales se examinan a la luz del texto bíblico.</p></article><article><strong>Gracia y verdad</strong><p>El amor dice verdad, recibe perdón, acepta consecuencias y busca cambio real.</p></article><article><strong>Cada temporada importa</strong><p>Matrimonio y paternidad se honran sin convertirlos en medida del valor adulto.</p></article><article><strong>Autoridad saludable</strong><p>El liderazgo sirve, escucha, protege, acepta responsabilidad y rechaza coerción.</p></article><article><strong>Seguridad y cuidado</strong><p>Abuso, peligro, trauma y necesidades graves requieren apoyo calificado y acción apropiada.</p></article></div></section>
 <div class="path-progress" aria-live="polite"><div class="path-progress-top"><strong>Tu progreso: ${count} de 10 estudios</strong><span>El progreso y las notas en español se guardan por separado en este dispositivo.</span></div><div class="path-progress-track"><i style="width:${count*10}%"></i></div></div>
 <section id="camino" class="section"><div class="section-heading"><p class="kicker">Camino completo de diez estudios</p><h2>De un fundamento en Cristo hacia un hogar que sirve y bendice.</h2></div><div class="mf-journey-grid">${studies.map(s=>`<article class="mf-study-card ${completed.includes(s.number)?'complete':''}"><span class="mf-study-number">${s.number}</span><div><h3>${s.title}</h3><p>${s.truth}</p><small>${s.main}</small><a href="${studyHref(s.number)}">${completed.includes(s.number)?'Revisar Estudio ✓':'Abrir Estudio →'}</a></div></article>`).join('')}</div></section>
 <section class="section mf-care"><div><p class="kicker">Seguridad y cuidado</p><h2>La unidad familiar nunca debe usarse para esconder daño.</h2><p>Este camino apoya matrimonio y vida familiar mientras rechaza violencia, control coercitivo, abuso infantil, coerción sexual, acecho, abuso financiero, intimidación espiritual y reconciliación forzada.</p></div><div><ul><li>Peligro inmediato requiere acción de emergencia y seguridad.</li><li>Revelaciones de abuso requieren política de iglesia, ley aplicable y apoyo calificado.</li><li>Perdonar no exige silencio, acceso restaurado ni permanecer inseguro.</li><li>Niños y adultos vulnerables deben ser protegidos.</li><li>El cuidado pastoral debe trabajar junto a recursos legales, clínicos, médicos y de defensa cuando corresponda.</li></ul></div></section>`;
}
function renderStudy(item){
 document.documentElement.lang='es';
 document.title=`${item.title} | Matrimonio y Familia`;
 const noteKey=`nldg-matrimonio-familia-notes-${item.number}`;
 const isDone=completed.includes(item.number);
 root.innerHTML=`
 <section class="mf-study-hero page-hero"><p class="study-label">Matrimonio y Familia • Estudio ${item.number} de 10</p><h1>${item.title}</h1><p class="lead">${item.truth}</p><div class="mf-study-meta"><span>📖 ${item.main}</span><span>Apoyo: ${item.supporting}</span><span>45–60 minutos</span><span>${item.theme}</span></div>${languageSwitch(item.english)}</section>
 <div class="mf-study-layout"><article class="mf-study-content">
 <section class="mf-block mf-highlight"><h2>Verdad bíblica central</h2><p><strong>${item.truth}</strong></p></section>
 <section class="mf-block"><h2>Enfoque de la Escritura</h2><p>Lee <strong>${item.main}</strong>. Después considera los pasajes de apoyo: <strong>${item.supporting}</strong>. Pregunta qué revela el texto acerca de Dios, dignidad humana, responsabilidad, amor, verdad, gracia y acción fiel.</p></section>
 <section class="mf-block mf-context"><h2>Contexto en lenguaje sencillo</h2>${item.context.map(p=>`<p>${p}</p>`).join('')}</section>
 ${item.movements.map(m=>`<section class="mf-block"><h2>${m[0]}</h2><p>${m[1]}</p></section>`).join('')}
 <section class="mf-block mf-jesus-connection"><h2>Conexión con Jesús</h2><p>${item.jesus}</p><h3>No confundas estas cosas</h3><ul>${item.distinctions.map(d=>`<li>${d}</li>`).join('')}</ul></section>
 <section class="mf-block"><h2>Preguntas para conversar</h2><ol>${item.questions.map(q=>`<li>${q}</li>`).join('')}</ol></section>
 <section class="mf-block"><h2>Vívelo esta semana</h2><p>${item.live}</p></section>
 <section class="mf-block mf-prayer"><h2>Oración</h2><p>${item.prayer}</p></section>
 <section class="mf-block"><h2>Nota para líderes y mentores</h2><p>${item.leader}</p><p><strong>Guardarraíl:</strong> Nunca uses sumisión, perdón, pacto, reconciliación, disciplina o unidad familiar para excusar abuso, acecho, coerción, control financiero, peligro infantil o acceso inseguro.</p></section>
 <section class="mf-block"><h2>Mi respuesta</h2><p>Escribe una oración, pregunta, verdad bíblica o próximo paso. Tus notas permanecen en este dispositivo.</p><textarea id="mfSpanishNotes" class="lesson-notes" rows="7" placeholder="¿Qué está mostrando Dios por medio de Su Palabra?"></textarea><div class="actions"><button id="saveMfSpanishNotes" class="button secondary" type="button">Guardar Notas</button><button id="completeMfSpanish" class="button primary" type="button">${isDone?'Estudio completado ✓':`Marcar Estudio ${item.number} como Completado`}</button></div><p id="mfSpanishStatus" class="lesson-status"></p></section>
 ${item.number===10?'<section class="mf-block mf-highlight"><h2>Camino completado</h2><p>Completaste los diez estudios de Matrimonio y Familia. Esto es un fundamento para seguir creciendo, no una declaración de que todo desafío relacional terminó.</p><p>Continúa en la Escritura, oración, comunidad cristiana saludable, conversaciones honestas, límites sabios, servicio práctico y apoyo calificado cuando sea necesario.</p></section>':''}
 <div class="lesson-actions mf-actions"><a class="button secondary" href="${item.number>1?studyHref(item.number-1):'matrimonio-familia.html'}">← ${item.number>1?'Estudio anterior':'Matrimonio y Familia'}</a><button class="button secondary" type="button" onclick="window.print()">Imprimir Estudio</button><a class="button primary" href="${item.number<10?studyHref(item.number+1):'matrimonio-familia.html'}">${item.number<10?'Próximo Estudio →':'Volver al Camino →'}</a></div>
 </article><aside class="mf-study-side"><div class="mf-side-card"><strong>Propósito del estudio</strong><p>${item.truth}</p></div><div class="mf-side-card"><strong>Escritura primero</strong><p>Lee en contexto y distingue lo que la Biblia dice claramente de interpretación, tradición y aplicación.</p></div><div class="mf-side-card"><strong>Gracia y seguridad</strong><p>La gracia nunca exige esconder abuso, ignorar peligro, silenciar niños o evitar ayuda calificada.</p></div></aside></div>`;
 const textarea=document.getElementById('mfSpanishNotes');textarea.value=localStorage.getItem(noteKey)||'';
 document.getElementById('saveMfSpanishNotes').onclick=()=>{localStorage.setItem(noteKey,textarea.value);const s=document.getElementById('mfSpanishStatus');s.textContent='Notas guardadas en este dispositivo.';setTimeout(()=>s.textContent='',2200)};
 document.getElementById('completeMfSpanish').onclick=()=>{let saved=JSON.parse(localStorage.getItem(progressKey)||'[]');if(!saved.includes(item.number))saved.push(item.number);saved.sort((a,b)=>a-b);localStorage.setItem(progressKey,JSON.stringify(saved));document.getElementById('completeMfSpanish').textContent='Estudio completado ✓';document.getElementById('mfSpanishStatus').textContent=item.number===10?'Completaste los diez estudios de Matrimonio y Familia.':'Tu progreso en español está guardado.';};
}
if(number){const item=studies.find(s=>s.number===number);item?renderStudy(item):renderLanding();}else renderLanding();
setTimeout(()=>window.NLDG_SCRIPTURE_LINKS?.linkReferences?.(root),0);
})();