(function(){
  const series=window.NLDG_PREPARING_WALK,hero=document.getElementById('prep-hero'),view=document.getElementById('prep-view');
  if(!series||!hero||!view)return;
  const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const params=new URLSearchParams(location.search),number=Number(params.get('lesson')||0),lesson=series.lessons.find(item=>item.number===number);
  const href=n=>`preparing-walk-with-jesus.html?lesson=${n}`;
  const progressKey='nldg-preparing-walk-completed';
  const readProgress=()=>{try{return new Set(JSON.parse(localStorage.getItem(progressKey)||'[]'))}catch{return new Set()}};
  const saveProgress=set=>{try{localStorage.setItem(progressKey,JSON.stringify([...set].sort()))}catch{}};
  const completed=readProgress();
  function landing(){
    document.title='Preparing to Walk with Jesus | No Labels, Designed by God';
    hero.innerHTML=`<div class="prep-hero-inner"><a class="series-back" href="walking-with-jesus.html">← Walking with Jesus</a><p class="kicker">Four-lesson Gospel foundation</p><h1>${esc(series.title)}</h1><p class="prep-lead">${esc(series.description)}</p><blockquote>${esc(series.theme)}</blockquote><div class="prep-meta"><span>📖 Gospel foundations</span><span>4 complete lessons</span><span>Use at your own pace</span></div></div>`;
    const next=series.lessons.find(item=>!completed.has(item.number))||series.lessons[0];
    view.innerHTML=`<section class="prep-intro"><p class="kicker">Before the journey</p><h2>Build the foundation before beginning the 21-week Gospel study.</h2><p>Move from understanding the four Gospel witnesses, to the identity of Jesus, to the cost of discipleship, and finally to a careful, Scripture-first way of reading.</p><div class="actions"><a class="button primary" href="${href(next.number)}">${completed.size?'Continue the series':'Begin Lesson 1'} →</a><a class="button secondary" href="walking-with-jesus.html">Main Walking with Jesus Series</a></div></section><section class="prep-grid">${series.lessons.map(item=>`<article class="prep-card ${completed.has(item.number)?'is-complete':''}"><span>Lesson ${item.number}${completed.has(item.number)?' · Completed':''}</span><h2>${esc(item.title)}</h2><p>${esc(item.question)}</p><small>📖 ${esc(item.scripture)}</small><a href="${href(item.number)}">Open Lesson →</a></article>`).join('')}</section><section class="prep-launch"><p class="kicker">Then continue the journey</p><h2>Walking with Jesus</h2><p>Begin the chronological Gospel study with Scripture first and optional scenes from <em>The Chosen</em> as discussion aids.</p><a class="button primary" href="walking-with-jesus-study.html?week=1">Begin the Main Series →</a></section>`;
  }
  function render(item){
    const index=series.lessons.indexOf(item),previous=series.lessons[index-1],next=series.lessons[index+1];
    document.title=`${item.title} | Preparing to Walk with Jesus`;
    document.body.dataset.studyPage=`preparing-walk-lesson-${item.number}`;
    hero.innerHTML=`<div class="prep-hero-inner"><a class="series-back" href="preparing-walk-with-jesus.html">← Series Overview</a><p class="kicker">Lesson ${item.number} of ${series.lessons.length}</p><h1>${esc(item.title)}</h1><p class="prep-lead">${esc(item.question)}</p><div class="prep-meta"><span>📖 ${esc(item.scripture)}</span><span>Use at your own pace</span></div></div>`;
    view.innerHTML=`<article class="prep-lesson"><section class="truth-banner"><p class="kicker">Focus</p><h2>${esc(item.focus)}</h2><p>${esc(item.truth)}</p></section><section class="lesson-panel"><p class="kicker">Opening discussion</p><p>${esc(item.opening)}</p></section><section class="lesson-panel scripture-panel"><p class="kicker">Read the Word</p><h2>${esc(item.scripture)}</h2>${item.intro.map(paragraph=>`<p>${esc(paragraph)}</p>`).join('')}</section>${item.movements.map((movement,i)=>`<section class="teaching-section"><div class="teaching-number">${i+1}</div><div><h2>${esc(movement.heading)}</h2>${movement.reference?`<p class="movement-reference">${esc(movement.reference)}</p>`:''}<p>${esc(movement.body)}</p></div></section>`).join('')}<section class="lesson-panel"><p class="kicker">Discuss</p><h2>Discussion Questions</h2><ol>${item.questions.map(question=>`<li>${esc(question)}</li>`).join('')}</ol></section><section class="challenge-panel"><p class="kicker">Weekly practice</p><h2>Live what you learned</h2><p>${esc(item.practice)}</p></section><section class="memory-panel"><p class="kicker">Memory verse</p><h2>${esc(item.memory)}</h2></section><section class="prayer-panel"><p class="kicker">Closing prayer</p><p>${esc(item.prayer)}</p></section><div class="complete-panel"><div><strong>${completed.has(item.number)?'Lesson completed':'Finished this lesson?'}</strong><span>Progress is saved on this device.</span></div><button id="prep-complete" class="button primary">${completed.has(item.number)?'Mark Incomplete':'Mark Complete'}</button></div><nav class="lesson-navigation" aria-label="Lesson navigation">${previous?`<a href="${href(previous.number)}">← Lesson ${previous.number}<strong>${esc(previous.title)}</strong></a>`:'<a href="preparing-walk-with-jesus.html">← Overview<strong>Preparing to Walk with Jesus</strong></a>'}${next?`<a href="${href(next.number)}">Lesson ${next.number} →<strong>${esc(next.title)}</strong></a>`:`<a href="walking-with-jesus-study.html?week=1">Continue →<strong>Begin Walking with Jesus</strong></a>`}</nav></article>`;
    document.getElementById('prep-complete').onclick=()=>{completed.has(item.number)?completed.delete(item.number):completed.add(item.number);saveProgress(completed);location.reload()};
  }
  lesson?render(lesson):landing();
})();
