(function(){
 const labels={cover:'Cover Page',participant:'Participant Guide',leader:'Leader Guide',teaching:'Teaching Outline',notebook:'Teaching Notebook',scripture:'Scripture Study Notes',resources:'Leader Resources and Extras',discussion:'Discussion Session Summary'};
 const privateIds=new Set(['notebook','scripture','resources','discussion']);
 const pageKey=()=>document.body.dataset.studyPage||`faith-truth-week-${new URLSearchParams(location.search).get('week')||'unknown'}`;
 const readKey=key=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}};
 const storageKey=()=>`nldg-print-center-${pageKey()}`;
 const read=()=>readKey(storageKey());
 const write=value=>{try{localStorage.setItem(storageKey(),JSON.stringify(value))}catch{}};
 const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
 const clean=value=>String(value||'').replace(/\s+/g,' ').trim();
 const unique=items=>[...new Set((items||[]).map(clean).filter(Boolean))];
 const refPattern=/\b(?:[1-3]\s)?[A-Z][a-z]+(?:\s+(?:of|the|[A-Z][a-z]+))*\s+\d+(?::\d+(?:[-–]\d+)?)?/g;
 const baseSections={cover:true,participant:true,leader:false,teaching:false,notebook:false,scripture:false,resources:false,discussion:false};
 const notebookState=()=>window.NLDGTeachingNotebook?.read?.()||readKey(`nldg-teaching-notebook-${pageKey()}`);
 const presets=()=>({
  participant:{label:'Participant Handout',detail:'Lesson content with room to write.',sections:{...baseSections},blankLines:true,compact:false},
  leader:{label:'Leader Preparation',detail:'Leader guide, Scripture notes, and resources.',sections:{...baseSections,participant:false,leader:true,scripture:true,resources:true},blankLines:false,compact:false},
  teaching:{label:'Teaching Packet',detail:'Condensed outline with optional notebook notes.',sections:{...baseSections,participant:false,teaching:true,notebook:Boolean(notebookState().includeInPrint)},blankLines:false,compact:true},
  followup:{label:'Follow-Up Packet',detail:'Discussion summary and follow-up notes.',sections:{...baseSections,cover:false,participant:false,discussion:true,notebook:true},blankLines:false,compact:true},
  complete:{label:'Complete Lesson Packet',detail:'Participant, leader, and teaching views.',sections:{...baseSections,leader:true,teaching:true,notebook:Boolean(notebookState().includeInPrint)},blankLines:true,compact:false}
 });
 const config=()=>{const saved=read();return{preset:saved.preset||'participant',sections:{...baseSections,...(saved.sections||{})},blankLines:saved.blankLines!==false,compact:Boolean(saved.compact),includeDate:saved.includeDate!==false}};
 const lessonData=()=>{
  const studyId=document.body.dataset.studyPage;
  const title=clean(document.querySelector('h1')?.textContent)||'Bible Study';
  if(studyId){
   const study=(window.NLDG_STUDIES||[]).find(item=>item.id===studyId)||{};
   const guide=window.NLDG_LEADER_GUIDES?.[studyId]||{};
   const visible=[...document.querySelectorAll('[class*="scripture"],[class*="verse"],.devo-ref')].map(node=>node.textContent).join(' ');
   return{title:study.title||title,subtitle:study.series||'No Labels, Designed by God',references:unique([...(study.scripture||[]),...(visible.match(refPattern)||[]),...(guide.connections||[]).flatMap(item=>String(item).match(refPattern)||[])]).slice(0,10),guide,lesson:null};
  }
  const week=Number(new URLSearchParams(location.search).get('week')||0);
  const lesson=window.NLDG_CURRENT_EVENTS_SERIES?.lessons?.find(item=>item.week===week)||{};
  return{title:lesson.title||title,subtitle:`Faith & Truth in Today's World${week?` · Week ${week}`:''}`,references:unique(lesson.scripture||[]),guide:lesson.leaderGuide||{},lesson};
 };
 const strip=(root,{values=false}={})=>{
  root.removeAttribute('hidden');root.querySelectorAll('[hidden]').forEach(node=>node.removeAttribute('hidden'));
  root.querySelectorAll('.expanded-leader-guide,.teaching-view-panel,.print-view-panel,.v2-leader-guide,.v2-teaching-view,.v2-print-view,.teaching-notebook,.study-notes,.lesson-actions,.series-navigation,.lesson-complete-panel,.study-view-controls,.study-experience-bar,.teaching-dashboard,.presentation-launch,.leader-resource-launch,.scripture-study-launch,.discussion-manager-launch,.print-center-launch,.lesson-sidebar,.series-lesson-nav,.section-navigation,.breadcrumbs,.content-sequence,.ministry-footer,script,style').forEach(node=>node.remove());
  root.querySelectorAll('button,input,select').forEach(node=>node.remove());
  root.querySelectorAll('textarea').forEach(field=>{const value=values?field.value.trim():'';if(value){const block=document.createElement('div');block.className='print-field-value';block.textContent=value;field.replaceWith(block)}else field.remove()});
  root.querySelectorAll('[id]').forEach(node=>node.removeAttribute('id'));
  return root;
 };
 const shell=(type,title,content)=>{const section=document.createElement('section');section.className=`print-packet-section print-packet-${type}`;section.innerHTML=`<header class="print-packet-section-head"><p>No Labels, Designed by God</p><h2>${esc(title)}</h2></header>`;if(content instanceof Node)section.appendChild(content);else section.insertAdjacentHTML('beforeend',content);return section};
 const participant=configValue=>{
  const source=document.querySelector('.v2-participant-guide')||document.querySelector('.lesson-wrap,.study-content,.wof-study-content,.mof-study-content,.mf-study-content,article');
  if(!source)return shell('participant','Participant Guide','<p>Participant content is not available on this page.</p>');
  const clone=strip(source.cloneNode(true));
  if(configValue.blankLines)clone.querySelectorAll('section').forEach(section=>{const heading=section.querySelector(':scope > h2,:scope > h3,:scope > h4');if(heading&&/discussion|conversation|questions|talk about|consider|reflect/i.test(heading.textContent))section.querySelectorAll('li').forEach(item=>item.insertAdjacentHTML('beforeend','<div class="print-answer-lines"><i></i><i></i></div>'))});
  return shell('participant','Participant Guide',clone);
 };
 const cloneView=(selector,type,title,options={})=>{const source=document.querySelector(selector);if(!source)return shell(type,title,`<p>${esc(title)} is not available for this lesson.</p>`);const clone=source.cloneNode(true);if(options.removeNotebook){clone.querySelectorAll('.teaching-notebook').forEach(node=>node.remove());clone.querySelectorAll('[data-v2-teaching-notes],[data-teaching-notes]').forEach(field=>field.closest('section')?.remove())}return shell(type,title,strip(clone,{values:options.values}))};
 const notebook=()=>{const state=notebookState();const names={objective:'Lesson Objective','big-idea':'Big Idea',opening:'Opening and Illustration',testimony:'Personal Story or Testimony','main-points':'Main Teaching Points',discussion:'Discussion Reminders',prayer:'Prayer Requests and Closing Prayer','follow-up':'Follow-Up Actions','next-week':'Next Lesson Preparation'};const entries=Object.entries(state.notes||{}).filter(([,value])=>String(value||'').trim());return shell('notebook','Teaching Notebook',entries.length?`<div class="print-note-grid">${entries.map(([id,value])=>`<article><h3>${esc(names[id]||id)}</h3><p>${esc(value).replaceAll('\n','<br>')}</p></article>`).join('')}</div>`:'<p>No teaching notebook notes have been saved for this lesson.</p>')};
 const scripture=()=>{const state=window.NLDGScriptureStudy?.read?.()||readKey(`nldg-scripture-study-${pageKey()}`);const studies=Object.entries(state.studies||{}).filter(([,record])=>Object.values(record||{}).some(value=>String(value||'').trim()));const names={keywords:'Key Words and Repeated Ideas',observation:'Observation',interpretation:'Interpretation',application:'Application and Prayer',questions:'Questions to Revisit'};const html=studies.length?studies.map(([reference,record])=>`<article class="print-study-record"><h3>${esc(reference)}</h3>${Object.entries(names).map(([key,label])=>String(record[key]||'').trim()?`<section><h4>${label}</h4><p>${esc(record[key]).replaceAll('\n','<br>')}</p></section>`:'').join('')}</article>`).join(''):'<p>No Scripture Study notes have been saved for this lesson.</p>';return shell('scripture','Scripture Study Notes',html)};
 const resources=data=>{const state=readKey(`nldg-leader-resources-${pageKey()}`),notes=state.notes||{},guide=data.guide||{};const background=Array.isArray(guide.background)?guide.background.map(item=>typeof item==='string'?item:`${item.heading||'Background'}: ${item.content||''}`):guide.background?[guide.background]:[];const theology=guide.theology||[];const connections=data.lesson?.resourceConnections?.map(item=>`${item.title}: ${item.detail}`)||guide.connections||[];const applications=Array.isArray(guide.application)?guide.application:Object.values(guide.ministryApplications||{}).flat();const blocks=[data.references.length?`<article><h3>Primary Scripture</h3><ul>${data.references.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`:'',background.length?`<article><h3>Biblical and Historical Context</h3>${background.map(item=>`<p>${esc(item)}</p>`).join('')}</article>`:'',theology.length?`<article><h3>Theological Themes</h3><ul>${theology.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`:'',connections.length?`<article><h3>Lesson Connections</h3><ul>${connections.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`:'',applications.length?`<article><h3>Application Ideas</h3><ul>${applications.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`:'',notes.chosen?.trim()?`<article><h3>The Chosen or Visual Media Connection</h3><p>${esc(notes.chosen).replaceAll('\n','<br>')}</p></article>`:'',notes.context?.trim()?`<article><h3>Map and Timeline Notes</h3><p>${esc(notes.context).replaceAll('\n','<br>')}</p></article>`:'',notes.extra?.trim()?`<article><h3>Additional Resource Ideas</h3><p>${esc(notes.extra).replaceAll('\n','<br>')}</p></article>`:''].filter(Boolean);return shell('resources','Leader Resources and Extras',blocks.length?`<div class="print-note-grid">${blocks.join('')}</div>`:'<p>No leader resources are available for this lesson.</p>')};
 const discussion=()=>{const summary=window.NLDGDiscussionManager?.summary?.()||'No discussion session has been saved for this lesson.';return shell('discussion','Discussion Session Summary',`<div class="print-preformatted">${esc(summary).replaceAll('\n','<br>')}</div>`)};
 const cover=data=>{const section=document.createElement('section');section.className='print-packet-cover';section.innerHTML=`<img src="no-labels-approved-logo.png" alt=""><p class="print-packet-ministry">No Labels, Designed by God</p><h1>${esc(data.title)}</h1><p class="print-packet-subtitle">${esc(data.subtitle)}</p>${data.references.length?`<div class="print-packet-references"><strong>Primary Scripture</strong><span>${data.references.map(esc).join(' · ')}</span></div>`:''}<p class="print-packet-purpose">Designed by God. Not defined by the world.</p>`;return section};
 const build=configValue=>{const data=lessonData();document.querySelector('.nldg-print-packet')?.remove();const packet=document.createElement('article');packet.className=`nldg-print-packet${configValue.compact?' is-compact':''}`;const selected=configValue.sections;if(selected.cover)packet.appendChild(cover(data));if(selected.participant)packet.appendChild(participant(configValue));if(selected.leader)packet.appendChild(cloneView('.v2-leader-guide,.expanded-leader-guide','leader','Leader Guide',{values:true}));if(selected.teaching)packet.appendChild(cloneView('.v2-teaching-view,.teaching-view-panel','teaching','Teaching Outline',{removeNotebook:true}));if(selected.notebook)packet.appendChild(notebook());if(selected.scripture)packet.appendChild(scripture());if(selected.resources)packet.appendChild(resources(data));if(selected.discussion)packet.appendChild(discussion());if(configValue.includeDate){const footer=document.createElement('footer');footer.className='print-packet-footer';footer.textContent=`Prepared ${new Intl.DateTimeFormat(undefined,{dateStyle:'long'}).format(new Date())} · nolabelsdesignedbygod.org`;packet.appendChild(footer)}document.body.appendChild(packet);return packet};
 let overlay,lastTrigger;
 const close=()=>{if(!overlay)return;overlay.hidden=true;document.body.classList.remove('print-center-open');lastTrigger?.focus?.()};
 const open=trigger=>{lastTrigger=trigger||document.activeElement;renderDialog();overlay.hidden=false;document.body.classList.add('print-center-open');overlay.querySelector('[data-print-center-close]').focus()};
 const applyPreset=(id,render)=>{const preset=presets()[id]||presets().participant;write({...config(),preset:id,sections:{...preset.sections},blankLines:preset.blankLines,compact:preset.compact});render()};
 const renderDialog=()=>{const data=lessonData(),state=config(),options=presets();overlay?.remove();overlay=document.createElement('div');overlay.className='print-center-overlay';overlay.hidden=true;overlay.innerHTML=`<section class="print-center" role="dialog" aria-modal="true" aria-labelledby="print-center-title"><header class="print-center-header"><div><p class="kicker">Phase 4.7</p><h2 id="print-center-title">Print Center</h2><p>${esc(data.title)}</p></div><button type="button" data-print-center-close>Close</button></header><main class="print-center-content"><section><div class="print-center-section-heading"><div><p class="kicker">Quick packets</p><h3>Choose a starting point.</h3></div></div><div class="print-preset-grid">${Object.entries(options).map(([id,preset])=>`<button type="button" data-print-preset="${id}" aria-pressed="${state.preset===id}"><strong>${preset.label}</strong><span>${preset.detail}</span></button>`).join('')}</div></section><section><div class="print-center-section-heading"><div><p class="kicker">Build your packet</p><h3>Select the sections you need.</h3></div><span>Private sections are clearly marked.</span></div><div class="print-section-grid">${Object.entries(labels).map(([id,label])=>`<label class="${privateIds.has(id)?'is-private':''}"><input type="checkbox" data-print-section="${id}" ${state.sections[id]?'checked':''}><span><strong>${label}</strong><small>${privateIds.has(id)?'Private notes from this device':'Lesson content'}</small></span></label>`).join('')}</div></section><section class="print-format-options"><div class="print-center-section-heading"><div><p class="kicker">Print format</p><h3>Make it useful in the room.</h3></div></div><label><input type="checkbox" data-print-option="blankLines" ${state.blankLines?'checked':''}><span><strong>Add response lines</strong><small>Places writing space beneath participant discussion questions.</small></span></label><label><input type="checkbox" data-print-option="compact" ${state.compact?'checked':''}><span><strong>Compact spacing</strong><small>Uses less paper for leader and teaching packets.</small></span></label><label><input type="checkbox" data-print-option="includeDate" ${state.includeDate?'checked':''}><span><strong>Include preparation date</strong><small>Adds a dated footer to the packet.</small></span></label></section><section class="print-packet-review"><div><p class="kicker">Packet review</p><h3 data-print-review-title></h3><p data-print-review-detail></p></div><ul data-print-review-list></ul></section></main><footer class="print-center-footer"><button type="button" data-print-now>Print or Save as PDF</button><span data-print-center-status aria-live="polite"></span></footer></section>`;document.body.appendChild(overlay);
  const render=()=>{const current=config();overlay.querySelectorAll('[data-print-preset]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.printPreset===current.preset)));overlay.querySelectorAll('[data-print-section]').forEach(field=>field.checked=Boolean(current.sections[field.dataset.printSection]));overlay.querySelectorAll('[data-print-option]').forEach(field=>field.checked=Boolean(current[field.dataset.printOption]));const selected=Object.entries(current.sections).filter(([,on])=>on).map(([id])=>id),privateCount=selected.filter(id=>privateIds.has(id)).length;overlay.querySelector('[data-print-review-title]').textContent=`${selected.length} section${selected.length===1?'':'s'} selected`;overlay.querySelector('[data-print-review-detail]').textContent=privateCount?`${privateCount} private section${privateCount===1?' is':'s are'} included. Review the packet before sharing.`:'No private notes are included.';overlay.querySelector('[data-print-review-list]').innerHTML=selected.length?selected.map(id=>`<li>${esc(labels[id])}${privateIds.has(id)?'<small>Private</small>':''}</li>`).join(''):'<li>Select at least one section.</li>'};
  overlay.querySelectorAll('[data-print-preset]').forEach(button=>button.addEventListener('click',()=>applyPreset(button.dataset.printPreset,render)));overlay.querySelectorAll('[data-print-section]').forEach(field=>field.addEventListener('change',()=>{const current=config();write({...current,preset:'custom',sections:{...current.sections,[field.dataset.printSection]:field.checked}});render()}));overlay.querySelectorAll('[data-print-option]').forEach(field=>field.addEventListener('change',()=>{const current=config();write({...current,preset:'custom',[field.dataset.printOption]:field.checked});render()}));overlay.querySelector('[data-print-center-close]').addEventListener('click',close);overlay.addEventListener('click',event=>{if(event.target===overlay)close()});overlay.querySelector('[data-print-now]').addEventListener('click',()=>{const current=config(),status=overlay.querySelector('[data-print-center-status]');if(!Object.values(current.sections).some(Boolean)){status.textContent='Select at least one packet section.';return}build(current);document.body.dataset.printCenterActive='true';status.textContent='Opening print preview…';const cleanup=()=>{delete document.body.dataset.printCenterActive;document.querySelector('.nldg-print-packet')?.remove();window.removeEventListener('afterprint',cleanup);if(overlay?.isConnected)status.textContent=''};window.addEventListener('afterprint',cleanup);window.print();setTimeout(()=>{if(document.body.dataset.printCenterActive)cleanup()},2500)});render()};
 document.addEventListener('keydown',event=>{if(!overlay||overlay.hidden)return;if(event.key==='Escape'){event.preventDefault();close();return}if(event.key!=='Tab')return;const focusable=[...overlay.querySelectorAll('button,input,[tabindex]:not([tabindex="-1"])')].filter(node=>!node.disabled&&!node.hidden&&node.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
 const attach=panel=>{if(!panel||panel.dataset.printCenterReady==='true')return;panel.dataset.printCenterReady='true';panel.querySelectorAll('.print-choice-grid,.v2-print-grid,.print-help').forEach(node=>node.hidden=true);const entry=document.createElement('section');entry.className='print-center-entry';entry.innerHTML='<div><p class="kicker">Unified Print Center</p><h3>Build one clean packet for the people in the room.</h3><p>Choose a quick preset or combine participant, leader, teaching, Scripture, resource, and follow-up sections.</p></div><button type="button" class="print-center-launch"><span>Open Print Center</span><small>Print or save as PDF</small></button>';entry.querySelector('button').addEventListener('click',event=>open(event.currentTarget));panel.appendChild(entry)};
 const find=()=>document.querySelectorAll('.print-view-panel,.v2-print-view').forEach(attach);find();new MutationObserver(find).observe(document.body,{childList:true,subtree:true});window.NLDGPrintCenter={open:()=>open(document.activeElement),build:()=>build(config()),read:()=>config()};
})();