const STORAGE_KEY='nldg-ministry-assistant-sessions-v7';
const FAVORITES_KEY='nldg-study-library-favorites-v1';
const results=document.querySelector('#libraryResults');
const empty=document.querySelector('#emptyLibrary');
const search=document.querySelector('#librarySearch');
const modeFilter=document.querySelector('#modeFilter');
const sortFilter=document.querySelector('#sortFilter');
const favoritesOnly=document.querySelector('#favoritesOnly');

function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function stripHtml(value){const element=document.createElement('div');element.innerHTML=value||'';return element.textContent||''}
function favorites(){return new Set(readJson(FAVORITES_KEY,[]))}
function saveFavorites(set){localStorage.setItem(FAVORITES_KEY,JSON.stringify([...set]))}
function sessions(){return readJson(STORAGE_KEY,[]).map(item=>({...item,updated:item.updated||item.created}))}
function labelFor(mode){return({bible:'Bible Study',sermon:'Sermon Prep',lesson:'Lesson Prep',group:'Small Group',coach:'Discipleship Coach',discover:'Content Discovery'})[mode]||'Study'}
function searchable(item){return [item.title,item.request,item.mode,item.study?.ref,item.study?.book,item.study?.themes?.join(' '),stripHtml(item.response),Object.values(item.notes||{}).join(' '),item.audience].join(' ').toLowerCase()}
function filteredSessions(){const query=search.value.trim().toLowerCase();const favs=favorites();let list=sessions().filter(item=>(modeFilter.value==='all'||item.mode===modeFilter.value)&&(!favoritesOnly.checked||favs.has(item.id))&&(!query||searchable(item).includes(query)));const sort=sortFilter.value;list.sort((a,b)=>{if(sort==='title')return String(a.title).localeCompare(String(b.title));if(sort==='passage')return String(a.study?.ref||'').localeCompare(String(b.study?.ref||''));if(sort==='created')return new Date(b.created)-new Date(a.created);return new Date(b.updated)-new Date(a.updated)});return list}
function openStudy(id){const item=sessions().find(entry=>entry.id===id);if(!item)return;localStorage.setItem('nldg-study-library-open',JSON.stringify(item));location.href='ministry-assistant.html'}
function toggleFavorite(id){const favs=favorites();favs.has(id)?favs.delete(id):favs.add(id);saveFavorites(favs);render()}
function archiveStudy(id){const list=sessions();const item=list.find(entry=>entry.id===id);if(!item)return;const archive=readJson('nldg-study-library-archive-v1',[]);archive.unshift({...item,archivedAt:new Date().toISOString()});localStorage.setItem('nldg-study-library-archive-v1',JSON.stringify(archive));localStorage.setItem(STORAGE_KEY,JSON.stringify(list.filter(entry=>entry.id!==id)));render()}
function render(){const list=filteredSessions();const all=sessions();const favs=favorites();document.querySelector('#studyCount').textContent=all.length;document.querySelector('#favoriteCount').textContent=all.filter(item=>favs.has(item.id)).length;document.querySelector('#passageCount').textContent=new Set(all.map(item=>item.study?.ref).filter(Boolean)).size;empty.hidden=list.length>0;results.hidden=list.length===0;results.innerHTML=list.map(item=>{const ref=item.study?.ref||'No passage saved';const themes=item.study?.themes||[];const preview=(Object.values(item.notes||{}).find(Boolean)||stripHtml(item.response)||item.request||'').slice(0,180);return `<article class="study-card"><p class="study-meta">${escapeHtml(labelFor(item.mode))} · ${escapeHtml(new Date(item.updated).toLocaleDateString())}</p><h2>${escapeHtml(item.title||ref)}</h2><p><strong>${escapeHtml(ref)}</strong></p><div class="study-tags">${themes.map(theme=>`<span>${escapeHtml(theme)}</span>`).join('')}</div><p class="study-preview">${escapeHtml(preview)}${preview.length===180?'…':''}</p><div class="study-actions"><button data-open="${escapeHtml(item.id)}">Continue</button><a href="ministry-tools.html" data-tools="${escapeHtml(item.id)}">Ministry Tools</a><button class="secondary" data-archive="${escapeHtml(item.id)}">Archive</button><button class="secondary favorite-button" data-favorite="${escapeHtml(item.id)}" aria-label="Toggle favorite">${favs.has(item.id)?'★':'☆'}</button></div></article>`}).join('');results.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openStudy(button.dataset.open)));results.querySelectorAll('[data-favorite]').forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favorite)));results.querySelectorAll('[data-archive]').forEach(button=>button.addEventListener('click',()=>archiveStudy(button.dataset.archive)));results.querySelectorAll('[data-tools]').forEach(link=>link.addEventListener('click',event=>{const item=sessions().find(entry=>entry.id===link.dataset.tools);if(!item)return;localStorage.setItem('nldg-ministry-tools-import',JSON.stringify({title:item.title||item.study?.ref||'Bible study',content:[item.request,Object.values(item.notes||{}).join('\n\n'),stripHtml(item.response)].filter(Boolean).join('\n\n'),source:'Sprint 7.2 Scripture Study Library'}))}))}
[search,modeFilter,sortFilter,favoritesOnly].forEach(control=>control.addEventListener(control===search?'input':'change',render));
render();
