window.NLDG_ARTICLES_ES=[
{
 id:'jesus-te-ama',sourceSlug:'jesus-loves-you',title:'Jesús te ama',excerpt:'Un letrero que dice «Jesús te ama» comunica una verdad poderosa. Los cristianos estamos llamados a hacer visibles esas palabras por medio de la compasión, la bondad y la acción.',category:'Vida cristiana',series:'Discipulado cotidiano',author:'Dexter Graham',publishedAt:'2026-07-30',readingTime:5,scripture:['Juan 13:34–35','1 Juan 3:18'],content:[
  {heading:'Más que palabras en un letrero',paragraphs:['Mientras conducía por una carretera conocida, vi un letrero con un mensaje sencillo: «Jesús te ama».','No tenía nada complicado. No era una explicación larga. No era un argumento. Solo tres palabras que declaraban una de las verdades más grandes que una persona puede escuchar.','Pero mientras seguía conduciendo, me vino otra pregunta: ¿Las personas que colocaron ese letrero viven como si Jesús realmente amara a la gente?','Al principio, la pregunta estaba dirigida hacia ellos. ¿Ayudan a quienes tienen necesidad? ¿Reciben a personas diferentes de ellos? ¿Muestran compasión a quienes están heridos, luchando, rechazados o incomprendidos?','Entonces entendí que la pregunta no era solamente para ellos. También era para mí.']},
  {heading:'El mensaje es verdadero',paragraphs:['Jesús ama a las personas.','Esa verdad no depende de qué tan bien lo representemos los cristianos. Nuestros fracasos no hacen menos real Su amor. Su amor nace de Su carácter, fue demostrado en la cruz y se ofrece a las personas antes de que tengan toda su vida en orden.','Pero la manera en que vivimos puede hacer que ese mensaje sea más fácil o más difícil de creer para otros.','Cuando los cristianos proclaman el amor de Jesús pero actúan con crueldad, arrogancia, deshonestidad o indiferencia, la gente nota la contradicción. Pueden comenzar a preguntarse si el mensaje del letrero significa algo más que palabras.','Jesús dijo a Sus discípulos que las personas los reconocerían por su amor unos por otros. El amor cristiano nunca fue destinado a ser solamente un lema, una calcomanía, una publicación en redes sociales o un letrero al lado del camino. Debía hacerse visible en la vida de quienes siguen a Jesús.']},
  {heading:'El amor debe hacerse visible',paragraphs:['Primera de Juan 3:18 llama a los creyentes a no amar solamente de palabra, sino con hechos y en verdad.','El amor se hace visible cuando escuchamos a alguien que se siente ignorado.','Se hace visible cuando damos de comer al hambriento, visitamos al que está solo, animamos al desalentado o permanecemos al lado de alguien que otros han rechazado.','El amor se hace visible cuando tratamos a las personas con dignidad aun cuando no estamos de acuerdo con ellas.','Se hace visible cuando perdonamos, servimos, damos, protegemos, recibimos y permanecemos presentes.','Esto no significa que el amor evite la verdad. Jesús amó lo suficiente como para confrontar el pecado, desafiar la hipocresía y llamar a las personas al arrepentimiento. Pero nunca trató a las personas quebrantadas como si fueran desechables.','Su verdad nunca estuvo separada de la compasión. La nuestra tampoco debería estarlo.']},
  {heading:'La pregunta vuelve hacia nosotros',paragraphs:['Es fácil evaluar si otros cristianos están viviendo el mensaje que proclaman. Es más difícil preguntar si nuestras propias acciones reflejan el amor de Jesús.','¿Las personas experimentan paciencia cuando se encuentran con nosotros?','¿Las personas más cercanas reciben nuestra bondad, o los desconocidos reciben nuestra mejor versión mientras la familia recibe lo que sobra?','¿Notamos a quienes se sienten invisibles?','¿Estamos dispuestos a ayudar cuando no recibiremos nada a cambio?','¿Nuestras iglesias reciben a personas que todavía no saben cómo vestirse, hablar, comportarse o encajar en la cultura de iglesia?','El mensaje «Jesús te ama» nunca debe convertirse en una excusa para evitar amar de verdad a las personas.','El letrero apunta hacia una verdad. Nuestra vida debería ayudar a demostrarla.']},
  {heading:'Que el letrero se convierta en una manera de vivir',paragraphs:['Un letrero al lado de la carretera puede recordarle a alguien que no ha sido olvidado. Puede ofrecer esperanza a una persona que lleva un dolor que nadie más puede ver. Esas tres palabras pueden llegar en el momento exacto.','Pero el mensaje no debe detenerse en el letrero.','Debe continuar en nuestras conversaciones, decisiones, iglesias, hogares, lugares de trabajo y comunidades.','«Jesús te ama» debe ser más que algo que decimos.','Debe cambiar la manera en que vemos a las personas.','Debe influir en cómo respondemos al sufrimiento.','Debe desafiar nuestros prejuicios, ablandar nuestro corazón y acercarnos a quienes se sienten rechazados o solos.','La próxima vez que veamos o compartamos esas palabras, quizá también debamos recibirlas como un desafío personal: Si Jesús ama a las personas, ¿cómo mostraré Su amor hoy?']}
 ],questions:['¿Mis acciones respaldan el mensaje de que Jesús ama a las personas?','¿Quién a mi alrededor puede sentirse ignorado, rechazado o incomprendido?','¿Hay alguien a quien Dios me está llamando a amar mediante una acción concreta?','¿La manera en que trato a las personas hace que el amor de Jesús sea más fácil o más difícil de ver?'],prayer:'Jesús, gracias por amarme con un amor que no gané. Ayúdame a hacer más que hablar de Tu amor. Enséñame a demostrarlo por medio de paciencia, compasión, verdad, generosidad y servicio. Muéstrame a las personas que he pasado por alto y dame valor para acercarme a ellas. Que mis palabras y acciones ayuden a otros a ver que Tu amor es real. Amén.'
},
{
 id:'fe-en-temporadas-dificiles',sourceSlug:'faith-hard-seasons',title:'Fe en temporadas difíciles',excerpt:'Las temporadas difíciles pueden cambiar nuestras rutinas, nuestra confianza y nuestros planes, pero no pueden quitar la presencia de Dios.',category:'Testimonios y reflexiones',series:'Fe en la vida real',author:'Dexter Graham',publishedAt:'2026-07-25',readingTime:5,scripture:['Salmo 46:1','Isaías 41:10'],content:[
  {heading:'La fe no niega la dificultad',paragraphs:['Confiar en Dios no exige fingir que el dolor es fácil. Las Escrituras nos dan permiso para lamentarnos, hacer preguntas y reconocer nuestra debilidad. La fe comienza llevando la verdad de nuestra experiencia a la presencia de Dios.']},
  {heading:'Dios muchas veces obra por medio de personas',paragraphs:['Durante temporadas difíciles, Dios con frecuencia hace visible Su cuidado a través de familiares, miembros de la iglesia, enfermeros, amigos e incluso desconocidos. Recibir ayuda no es un fracaso de fe. Puede ser una de las maneras en que experimentamos el cuerpo de Cristo.']},
  {heading:'La fuerza llega un día a la vez',paragraphs:['Muchas veces queremos conocer el plan completo, pero Dios suele darnos la gracia suficiente para el día presente. La perseverancia crece mediante pequeños actos de confianza: volver a orar, volver a presentarnos, aceptar ayuda y creer que Dios todavía está presente.']}
 ],questions:['¿Qué ha revelado una temporada difícil acerca de tu fe?','¿A quién ha usado Dios para sostenerte?','¿Cómo se ve la fidelidad para ti hoy?'],prayer:'Dios, sé mi refugio y mi fortaleza. Ayúdame a confiar en Ti un día a la vez y a reconocer Tu presencia en las personas y en la gracia que Tú provees.'
},
{
 id:'la-gracia-no-elimina-la-responsabilidad',sourceSlug:'grace-accountability',title:'La gracia no elimina la responsabilidad',excerpt:'La gracia bíblica dice la verdad acerca del pecado mientras protege la dignidad de la persona que necesita restauración.',category:'Vida cristiana',series:'Discipulado cotidiano',author:'Dexter Graham',publishedAt:'2026-07-26',readingTime:6,scripture:['Juan 1:14','Gálatas 6:1–2'],content:[
  {heading:'La gracia y la verdad van juntas',paragraphs:['Jesús no escogió entre gracia y verdad. Juan lo describe lleno de ambas. La gracia sin verdad puede convertirse en permiso, mientras que la verdad sin gracia puede convertirse en condenación. El camino de Jesús confronta lo que está mal y al mismo tiempo sigue viendo a una persona creada a imagen de Dios.']},
  {heading:'La responsabilidad busca restaurar',paragraphs:['La responsabilidad bíblica no es humillación pública ni el deseo de hacer sufrir a alguien. Es la obra amorosa de ayudarnos unos a otros a regresar a la fidelidad. Gálatas 6 dice que quienes son espirituales deben restaurar con gentileza y vigilar también su propio corazón mientras lo hacen.']},
  {heading:'La dignidad permanece',paragraphs:['Una persona puede necesitar corrección, límites, consecuencias o tiempo para reconstruir la confianza. Ninguna de esas cosas elimina su valor dado por Dios. Los cristianos deberíamos poder insistir en la responsabilidad sin crueldad y ofrecer misericordia sin fingir que el daño nunca ocurrió.']}
 ],questions:['¿Tiendes a enfatizar más la gracia o la responsabilidad?','¿Cómo puede la corrección buscar restauración en lugar de humillación?','¿Dónde puede Dios estar llamándote a unir la verdad con la gentileza?'],prayer:'Señor, enséñame a hablar la verdad sin orgullo y a extender gracia sin compromiso con el error. Ayúdame a buscar restauración, proteger la dignidad y reflejar el corazón de Jesús.'
},
{
 id:'antes-de-compartir',sourceSlug:'truth-online',title:'Antes de compartir: verdad, discernimiento y redes sociales',excerpt:'Nuestro testimonio cristiano también incluye lo que publicamos, repetimos y respaldamos en internet.',category:'Fe y el mundo de hoy',series:'Seguir a Jesús en internet',author:'Dexter Graham',publishedAt:'2026-07-24',readingTime:7,scripture:['Proverbios 14:15','Santiago 3:5–10'],content:[
  {heading:'La velocidad trabaja contra la sabiduría',paragraphs:['Las redes sociales recompensan las reacciones inmediatas. La sabiduría bíblica nos llama a reducir la velocidad, examinar una afirmación y considerar el efecto de nuestras palabras antes de compartirlas. Ser el primero no es más importante que ser veraz.']},
  {heading:'Nuestro testimonio viaja con nuestras palabras',paragraphs:['Una publicación puede parecer temporal, pero puede influir en la manera en que otros ven nuestro carácter y nuestra fe. Los cristianos no deberíamos preguntarnos solamente si un mensaje apoya nuestra posición, sino también si es correcto, necesario y expresado de una manera semejante a Cristo.']},
  {heading:'Practica una pausa santa',paragraphs:['Antes de publicar, verifica la fuente, busca confirmación confiable, lee más allá del titular y ora. A veces la respuesta más fiel es corregir. Otras veces, es guardar silencio.']}
 ],questions:['¿Qué te hace más propenso a compartir algo rápidamente?','¿Cómo puede la desinformación dañar el testimonio cristiano?','¿Qué práctica podría ayudarte a hacer una pausa antes de publicar?'],prayer:'Señor, dame sabiduría antes de hablar o compartir. Que mis palabras sean verdaderas, útiles y moldeadas por el carácter de Cristo.'
}
];
window.NLDG_ARTICLES_ES_API={all:()=>[...window.NLDG_ARTICLES_ES],byId:id=>window.NLDG_ARTICLES_ES.find(item=>item.id===id),related:(article,limit=3)=>window.NLDG_ARTICLES_ES.filter(item=>item.id!==article.id).slice(0,limit)};
