#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const inputPath = process.argv[2] || 'tools/content-importer/drive-export.json';
const outputPath = process.argv[3] || 'content-import.generated.js';

if (!fs.existsSync(inputPath)) {
  console.error(`Missing import file: ${inputPath}`);
  process.exit(1);
}

const raw = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const files = Array.isArray(raw) ? raw : raw.files;
if (!Array.isArray(files)) throw new Error('Import file must contain an array or { files: [] }.');

const slugify = value => String(value || 'untitled')
  .toLowerCase()
  .normalize('NFKD')
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-|-$/g, '');

function classify(file) {
  const haystack = `${file.title || ''} ${(file.folderPath || []).join(' ')}`.toLowerCase();
  if (/sunday school|ss wk|lesson/.test(haystack)) return 'sunday-school';
  if (/devotional|devotion/.test(haystack)) return 'devotional';
  if (/article/.test(haystack)) return 'article';
  if (/wednesday/.test(haystack)) return 'wednesday-study';
  return 'bible-study';
}

function scriptureRefs(text) {
  const pattern = /\b(?:Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|Samuel|Kings|Chronicles|Ezra|Nehemiah|Esther|Job|Psalms?|Proverbs|Ecclesiastes|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|Corinthians|Galatians|Ephesians|Philippians|Colossians|Thessalonians|Timothy|Titus|Philemon|Hebrews|James|Peter|Jude|Revelation)\s+\d+(?::\d+(?:-\d+)?)?/gi;
  return [...new Set((text.match(pattern) || []).map(v => v.trim()))].slice(0, 12);
}

function splitQuestions(lines) {
  const questions = [];
  const body = [];
  let inQuestions = false;
  for (const line of lines) {
    if (/discussion questions?|reflection questions?|questions? for discussion/i.test(line)) {
      inQuestions = true;
      continue;
    }
    if (inQuestions && /^(?:\d+[.)]|[-•])\s+/.test(line) && /\?$/.test(line)) {
      questions.push(line.replace(/^(?:\d+[.)]|[-•])\s+/, '').trim());
    } else if (line.trim()) {
      body.push(line.trim());
    }
  }
  return { body, questions };
}

function sectionsFrom(body) {
  const sections = [];
  let current = { heading: 'Lesson', content: [] };
  for (const line of body) {
    const looksLikeHeading = line.length < 90 && !/[.!?]$/.test(line) && /^(introduction|opening|overview|background|scripture|explore|application|conclusion|closing|lesson|week|part|\d+[.)])/i.test(line);
    if (looksLikeHeading && current.content.length) {
      sections.push(current);
      current = { heading: line.replace(/^\d+[.)]\s*/, ''), content: [] };
    } else {
      current.content.push(line);
    }
  }
  if (current.content.length) sections.push(current);
  return sections;
}

function transform(file) {
  const content = String(file.content || '').replace(/^\uFEFF/, '').trim();
  const lines = content.split(/\r?\n/).map(v => v.trim()).filter(Boolean);
  const { body, questions } = splitQuestions(lines);
  const type = classify(file);
  return {
    id: slugify(file.title),
    sourceId: file.id || null,
    sourceUrl: file.url || null,
    title: file.title || 'Untitled',
    description: body[0] || 'Imported ministry content.',
    scripture: scriptureRefs(content),
    category: type === 'sunday-school' ? 'Sunday School' : 'Christian Living',
    series: (file.folderPath || []).at(-1) || 'Imported Lessons',
    audience: ['Adults', 'Small Groups'],
    duration: 45,
    status: 'draft',
    publishedAt: null,
    contentType: type,
    sections: sectionsFrom(body),
    questions,
    prayer: '',
    importedAt: new Date().toISOString(),
    sourceModifiedTime: file.modifiedTime || null
  };
}

const imported = files.filter(file => file && file.content).map(transform);
const groups = {
  sundaySchool: imported.filter(v => v.contentType === 'sunday-school'),
  bibleStudies: imported.filter(v => v.contentType === 'bible-study' || v.contentType === 'wednesday-study'),
  devotionals: imported.filter(v => v.contentType === 'devotional'),
  articles: imported.filter(v => v.contentType === 'article')
};

const output = `// Generated by tools/content-importer/import-content.mjs\n` +
  `window.NLDG_IMPORTED_CONTENT = ${JSON.stringify(groups, null, 2)};\n`;
fs.writeFileSync(outputPath, output);
console.log(`Imported ${imported.length} files to ${path.resolve(outputPath)}`);
console.log(Object.fromEntries(Object.entries(groups).map(([key, value]) => [key, value.length])));
